In [7]:

import os

data_path = r"C:\Users\hp\Desktop\nassau factory optimization\data\dataset.csv"

print("File exists:", os.path.exists(data_path))
print("File size:", os.path.getsize(data_path), "bytes")

File exists: True
File size: 1979595 bytes

In [9]:
import pandas as pd
import numpy as np

# Path to the original dataset
data_path = r"C:\Users\hp\Desktop\nassau factory optimization\data\dataset.csv"

# Load the dataset
df = pd.read_csv(data_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (10194, 18)

In [11]:
# NASSAU CANDY - COMPLETE DATASET AUDITprint("=" * 70)
print("1. COLUMN NAMES")
print("=" * 70)

for i, column in enumerate(df.columns, 1):
    print(f"{i:2}. {column}")


print("\n" + "=" * 70)
print("2. FIRST 5 RECORDS")
print("=" * 70)

display(df.head())


print("\n" + "=" * 70)
print("3. DATA TYPES")
print("=" * 70)

display(df.dtypes.to_frame(name="Data Type"))


print("\n" + "=" * 70)
print("4. MISSING VALUES")
print("=" * 70)

missing_count = df.isnull().sum()
missing_percentage = (missing_count / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing %": missing_percentage
})

display(missing_report)


print("\n" + "=" * 70)
print("5. DUPLICATE RECORDS")
print("=" * 70)

print("Duplicate rows:", df.duplicated().sum())


print("\n" + "=" * 70)
print("6. NUMERICAL SUMMARY")
print("=" * 70)

display(df.describe().T)

1. COLUMN NAMES
======================================================================
 1. Row ID
 2. Order ID
 3. Order Date
 4. Ship Date
 5. Ship Mode
 6. Customer ID
 7. Country/Region
 8. City
 9. State/Province
10. Postal Code
11. Division
12. Region
13. Product ID
14. Product Name
15. Sales
16. Units
17. Gross Profit
18. Cost

======================================================================
2. FIRST 5 RECORDS
======================================================================

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

======================================================================
3. DATA TYPES
======================================================================

               Data Type
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID        int64
Country/Region    object
City              object
State/Province    object
Postal Code       object
Division          object
Region            object
Product ID        object
Product Name      object
Sales            float64
Units              int64
Gross Profit     float64
Cost             float64

======================================================================
4. MISSING VALUES
======================================================================

                Missing Count  Missing %
Row ID                      0        0.0
Order ID                    0        0.0
Order Date                  0        0.0
Ship Date                   0        0.0
Ship Mode                   0        0.0
Customer ID                 0        0.0
Country/Region              0        0.0
City                        0        0.0
State/Province              0        0.0
Postal Code                 0        0.0
Division                    0        0.0
Region                      0        0.0
Product ID                  0        0.0
Product Name                0        0.0
Sales                       0        0.0
Units                       0        0.0
Gross Profit                0        0.0
Cost                        0        0.0

======================================================================
5. DUPLICATE RECORDS
======================================================================
Duplicate rows: 0

======================================================================
6. NUMERICAL SUMMARY
======================================================================

,count,mean,std,min,25%,50%,75%,max
Row ID,10194.0,5097.500000,2942.898656,1.00,2549.25,5097.50,7645.75,10194.0
Customer ID,10194.0,134468.961154,20231.483007,100006.00,117212.00,133550.00,152051.00,192314.0
Sales,10194.0,13.908537,11.341020,1.25,7.20,10.80,18.00,260.0
Units,10194.0,3.791838,2.228317,1.00,2.00,3.00,5.00,14.0
Gross Profit,10194.0,9.166451,6.643740,0.25,4.90,7.47,12.25,130.0
Cost,10194.0,4.742087,5.061647,0.60,2.40,3.60,5.70,130.0

In [13]:
# ============================================
# STEP 2: DATE VALIDATION & LEAD-TIME ANALYSIS
# ============================================

# Make a copy so the original dataframe remains untouched
df_analysis = df.copy()

# Convert dates to datetime
df_analysis["Order Date"] = pd.to_datetime(
    df_analysis["Order Date"],
    dayfirst=True,
    errors="coerce"
)

df_analysis["Ship Date"] = pd.to_datetime(
    df_analysis["Ship Date"],
    dayfirst=True,
    errors="coerce"
)

# Check whether any dates failed to convert
print("=" * 70)
print("DATE CONVERSION CHECK")
print("=" * 70)

print("Invalid Order Dates:",
      df_analysis["Order Date"].isna().sum())

print("Invalid Ship Dates:",
      df_analysis["Ship Date"].isna().sum())


# Calculate shipping lead time
df_analysis["Shipping Lead Time"] = (
    df_analysis["Ship Date"] - df_analysis["Order Date"]
).dt.days

print("\n" + "=" * 70)
print("SHIPPING LEAD TIME SUMMARY")
print("=" * 70)

display(
    df_analysis["Shipping Lead Time"].describe()
)


# Check negative lead times
print("\n" + "=" * 70)
print("INVALID / NEGATIVE LEAD TIMES")
print("=" * 70)

negative_lead_time = (
    df_analysis["Shipping Lead Time"] < 0
).sum()

print("Negative lead-time records:", negative_lead_time)


# Show the longest shipping times
print("\n" + "=" * 70)
print("LONGEST SHIPPING LEAD TIMES")
print("=" * 70)

longest_shipments = (
    df_analysis[
        [
            "Order ID",
            "Order Date",
            "Ship Date",
            "Ship Mode",
            "Region",
            "Product Name",
            "Shipping Lead Time"
        ]
    ]
    .sort_values("Shipping Lead Time", ascending=False)
    .head(20)
)

display(longest_shipments)


# Distribution of lead time
print("\n" + "=" * 70)
print("LEAD-TIME FREQUENCY")
print("=" * 70)

display(
    df_analysis["Shipping Lead Time"]
    .value_counts()
    .sort_index()
    .head(30)
)

======================================================================
DATE CONVERSION CHECK
======================================================================
Invalid Order Dates: 0
Invalid Ship Dates: 0

======================================================================
SHIPPING LEAD TIME SUMMARY
======================================================================

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Shipping Lead Time, dtype: float64

======================================================================
INVALID / NEGATIVE LEAD TIMES
======================================================================
Negative lead-time records: 0

======================================================================
LONGEST SHIPPING LEAD TIMES
======================================================================

,Order ID,Order Date,Ship Date,Ship Mode,Region,Product Name,Shipping Lead Time
7974,US-2024-133648-CHO-MIL-31000,2025-06-25,2029-12-23,Standard Class,Pacific,Wonka Bar - Milk Chocolate,1642
8649,US-2024-123036-CHO-MIL-31000,2025-09-10,2030-03-10,Standard Class,Atlantic,Wonka Bar - Milk Chocolate,1642
9162,US-2024-113453-CHO-MIL-31000,2025-10-21,2030-04-20,Standard Class,Atlantic,Wonka Bar - Milk Chocolate,1642
8952,US-2024-156951-CHO-MIL-31000,2025-10-01,2030-03-31,Standard Class,Pacific,Wonka Bar - Milk Chocolate,1642
9158,US-2024-113453-CHO-NUT-13000,2025-10-21,2030-04-20,Standard Class,Atlantic,Wonka Bar - Nutty Crunch Surprise,1642
9155,US-2024-117331-CHO-SCR-58000,2025-10-21,2030-04-20,Standard Class,Pacific,Wonka Bar -Scrumdiddlyumptious,1642
8375,US-2024-119809-CHO-MIL-31000,2025-08-18,2030-02-15,Standard Class,Pacific,Wonka Bar - Milk Chocolate,1642
8372,US-2024-122028-CHO-FUD-51000,2025-08-18,2030-02-15,Standard Class,Atlantic,Wonka Bar - Fudge Mallows,1642
8371,US-2024-119809-CHO-TRI-54000,2025-08-18,2030-02-15,Standard Class,Pacific,Wonka Bar - Triple Dazzle Caramel,1642
8058,US-2024-124303-CHO-MIL-31000,2025-07-06,2030-01-03,Standard Class,Atlantic,Wonka Bar - Milk Chocolate,1642
8059,US-2024-124303-CHO-FUD-51000,2025-07-06,2030-01-03,Standard Class,Atlantic,Wonka Bar - Fudge Mallows,1642
8365,US-2024-119809-CHO-TRI-54000,2025-08-18,2030-02-15,Standard Class,Pacific,Wonka Bar - Triple Dazzle Caramel,1642
9140,US-2024-158743-CHO-SCR-58000,2025-10-20,2030-04-19,Standard Class,Gulf,Wonka Bar -Scrumdiddlyumptious,1642
9508,US-2024-118122-CHO-TRI-54000,2025-11-17,2030-05-17,Standard Class,Pacific,Wonka Bar - Triple Dazzle Caramel,1642
8071,US-2024-108560-CHO-TRI-54000,2025-07-08,2030-01-05,Standard Class,Pacific,Wonka Bar - Triple Dazzle Caramel,1642
9135,US-2024-158743-CHO-FUD-51000,2025-10-20,2030-04-19,Standard Class,Gulf,Wonka Bar - Fudge Mallows,1642
8362,US-2024-166093-CHO-MIL-31000,2025-08-17,2030-02-14,Standard Class,Pacific,Wonka Bar - Milk Chocolate,1642
9132,US-2024-158743-CHO-MIL-31000,2025-10-20,2030-04-19,Standard Class,Gulf,Wonka Bar - Milk Chocolate,1642
9126,US-2024-159457-CHO-SCR-58000,2025-10-19,2030-04-18,Standard Class,Interior,Wonka Bar -Scrumdiddlyumptious,1642
8360,US-2024-133102-CHO-FUD-51000,2025-08-17,2030-02-14,Standard Class,Interior,Wonka Bar - Fudge Mallows,1642

======================================================================
LEAD-TIME FREQUENCY
======================================================================

Shipping Lead Time
904       89
905       40
906      289
907      176
908      591
909      519
910      207
911      134
912        4
915        2
1269     258
1270     156
1271     610
1272     456
1273    1326
1274    1035
1275     612
1276     293
1277      18
1634       3
1635     179
1636     190
1637     449
1638     411
1639     896
1640     657
1641     397
1642     197
Name: count, dtype: int64

In [15]:
# ============================================
# INVESTIGATE EXTREME LEAD TIMES
# ============================================

print("=" * 70)
print("EXTREME LEAD-TIME INVESTIGATION")
print("=" * 70)

extreme_records = (
    df_analysis[
        [
            "Order ID",
            "Order Date",
            "Ship Date",
            "Ship Mode",
            "Country/Region",
            "City",
            "State/Province",
            "Division",
            "Region",
            "Product ID",
            "Product Name",
            "Sales",
            "Units",
            "Gross Profit",
            "Cost",
            "Shipping Lead Time"
        ]
    ]
    .sort_values("Shipping Lead Time", ascending=False)
    .head(20)
)

display(extreme_records)

======================================================================
EXTREME LEAD-TIME INVESTIGATION
======================================================================

,Order ID,Order Date,Ship Date,Ship Mode,Country/Region,City,State/Province,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time
7974,US-2024-133648-CHO-MIL-31000,2025-06-25,2029-12-23,Standard Class,United States,Springfield,Oregon,Chocolate,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,1642
8649,US-2024-123036-CHO-MIL-31000,2025-09-10,2030-03-10,Standard Class,United States,Springfield,Ohio,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,1642
9162,US-2024-113453-CHO-MIL-31000,2025-10-21,2030-04-20,Standard Class,United States,Philadelphia,Pennsylvania,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,1642
8952,US-2024-156951-CHO-MIL-31000,2025-10-01,2030-03-31,Standard Class,United States,Seattle,Washington,Chocolate,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate,26.00,8,16.88,9.12,1642
9158,US-2024-113453-CHO-NUT-13000,2025-10-21,2030-04-20,Standard Class,United States,Philadelphia,Pennsylvania,Chocolate,Atlantic,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,1642
9155,US-2024-117331-CHO-SCR-58000,2025-10-21,2030-04-20,Standard Class,United States,Glendale,Arizona,Chocolate,Pacific,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,3.60,1,2.50,1.10,1642
8375,US-2024-119809-CHO-MIL-31000,2025-08-18,2030-02-15,Standard Class,United States,Seattle,Washington,Chocolate,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate,22.75,7,14.77,7.98,1642
8372,US-2024-122028-CHO-FUD-51000,2025-08-18,2030-02-15,Standard Class,United States,Lakewood,Ohio,Chocolate,Atlantic,CHO-FUD-51000,Wonka Bar - Fudge Mallows,10.80,3,7.20,3.60,1642
8371,US-2024-119809-CHO-TRI-54000,2025-08-18,2030-02-15,Standard Class,United States,Seattle,Washington,Chocolate,Pacific,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,33.75,9,22.05,11.70,1642
8058,US-2024-124303-CHO-MIL-31000,2025-07-06,2030-01-03,Standard Class,United States,Philadelphia,Pennsylvania,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,1642
8059,US-2024-124303-CHO-FUD-51000,2025-07-06,2030-01-03,Standard Class,United States,Philadelphia,Pennsylvania,Chocolate,Atlantic,CHO-FUD-51000,Wonka Bar - Fudge Mallows,10.80,3,7.20,3.60,1642
8365,US-2024-119809-CHO-TRI-54000,2025-08-18,2030-02-15,Standard Class,United States,Seattle,Washington,Chocolate,Pacific,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,1642
9140,US-2024-158743-CHO-SCR-58000,2025-10-20,2030-04-19,Standard Class,United States,Little Rock,Arkansas,Chocolate,Gulf,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,7.20,2,5.00,2.20,1642
9508,US-2024-118122-CHO-TRI-54000,2025-11-17,2030-05-17,Standard Class,United States,Seattle,Washington,Chocolate,Pacific,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,1642
8071,US-2024-108560-CHO-TRI-54000,2025-07-08,2030-01-05,Standard Class,United States,Kent,Washington,Chocolate,Pacific,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,1642
9135,US-2024-158743-CHO-FUD-51000,2025-10-20,2030-04-19,Standard Class,United States,Little Rock,Arkansas,Chocolate,Gulf,CHO-FUD-51000,Wonka Bar - Fudge Mallows,18.00,5,12.00,6.00,1642
8362,US-2024-166093-CHO-MIL-31000,2025-08-17,2030-02-14,Standard Class,United States,Brentwood,California,Chocolate,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42,1642
9132,US-2024-158743-CHO-MIL-31000,2025-10-20,2030-04-19,Standard Class,United States,Little Rock,Arkansas,Chocolate,Gulf,CHO-MIL-31000,Wonka Bar - Milk Chocolate,13.00,4,8.44,4.56,1642
9126,US-2024-159457-CHO-SCR-58000,2025-10-19,2030-04-18,Standard Class,United States,Houston,Texas,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,1642
8360,US-2024-133102-CHO-FUD-51000,2025-08-17,2030-02-14,Standard Class,United States,Houston,Texas,Chocolate,Interior,CHO-FUD-51000,Wonka Bar - Fudge Mallows,7.20,2,4.80,2.40,1642

In [17]:
# ============================================
# STEP 3: FACTORY-PRODUCT MAPPING
# ============================================

factory_mapping = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",

    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",

    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",

    "Fizzy Lifting Drinks": "Sugar Shack",

    "Everlasting Gobstopper": "Secret Factory",

    "Hair Toffee": "The Other Factory",

    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",

    "Kazookles": "The Other Factory"
}

# Create a new factory column
df_analysis["Current Factory"] = (
    df_analysis["Product Name"].map(factory_mapping)
)

print("=" * 70)
print("FACTORY MAPPING RESULTS")
print("=" * 70)

print(
    "Products in dataset:",
    df_analysis["Product Name"].nunique()
)

print(
    "Products successfully mapped:",
    df_analysis["Current Factory"].notna().sum()
)

print(
    "Records without factory mapping:",
    df_analysis["Current Factory"].isna().sum()
)

print("\nFactory distribution:")

display(
    df_analysis["Current Factory"]
    .value_counts()
)

======================================================================
FACTORY MAPPING RESULTS
======================================================================
Products in dataset: 15
Products successfully mapped: 10194
Records without factory mapping: 0

Factory distribution:

Current Factory
Lot's O' Nuts        5692
Wicked Choccy's      4152
Secret Factory        217
The Other Factory     100
Sugar Shack            33
Name: count, dtype: int64

In [32]:
# ============================================
# VERIFY PRODUCT → FACTORY MAPPING
# ============================================

product_factory_check = (
    df_analysis[
        ["Product ID", "Product Name", "Division", "Current Factory"]
    ]
    .drop_duplicates()
    .sort_values(["Current Factory", "Product Name"])
)

display(product_factory_check)

,Product ID,Product Name,Division,Current Factory
13,CHO-FUD-51000,Wonka Bar - Fudge Mallows,Chocolate,Lot's O' Nuts
2,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Chocolate,Lot's O' Nuts
3,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,Chocolate,Lot's O' Nuts
4729,SUG-EVE-47000,Everlasting Gobstopper,Sugar,Secret Factory
136,OTH-LIC-15000,Lickable Wallpaper,Other,Secret Factory
19,OTH-GUM-21000,Wonka Gum,Other,Secret Factory
191,OTH-FIZ-56000,Fizzy Lifting Drinks,Sugar,Sugar Shack
5007,SUG-FUN-75000,Fun Dip,Sugar,Sugar Shack
226,SUG-LAF-25000,Laffy Taffy,Sugar,Sugar Shack
1490,SUG-NER-92000,Nerds,Sugar,Sugar Shack
973,SUG-SWE-91000,SweeTARTS,Sugar,Sugar Shack
4435,SUG-HAI-55000,Hair Toffee,Sugar,The Other Factory
26,OTH-KAZ-38000,Kazookles,Other,The Other Factory
0,CHO-MIL-31000,Wonka Bar - Milk Chocolate,Chocolate,Wicked Choccy's
1,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Chocolate,Wicked Choccy's

In [39]:
# ============================================
# STEP 5: CUSTOMER LOCATION ANALYSIS
# ============================================

print("=" * 70)
print("CUSTOMER GEOGRAPHIC COVERAGE")
print("=" * 70)

print("Unique cities:", df_analysis["City"].nunique())
print("Unique states:", df_analysis["State/Province"].nunique())
print("Unique postal codes:", df_analysis["Postal Code"].nunique())

print("\n" + "=" * 70)
print("TOP CUSTOMER STATES")
print("=" * 70)

display(
    df_analysis["State/Province"]
    .value_counts()
    .head(20)
)

print("\n" + "=" * 70)
print("TOP CUSTOMER CITIES")
print("=" * 70)

display(
    df_analysis["City"]
    .value_counts()
    .head(20)
)

print("\n" + "=" * 70)
print("COUNTRIES")
print("=" * 70)

display(
    df_analysis["Country/Region"]
    .value_counts()
)

======================================================================
CUSTOMER GEOGRAPHIC COVERAGE
======================================================================
Unique cities: 542
Unique states: 59
Unique postal codes: 654

======================================================================
TOP CUSTOMER STATES
======================================================================

State/Province
California        2001
New York          1128
Texas              985
Pennsylvania       587
Washington         506
Illinois           492
Ohio               469
Florida            383
Michigan           255
North Carolina     249
Virginia           224
Arizona            224
Georgia            184
Tennessee          183
Colorado           182
Indiana            149
Kentucky           139
Massachusetts      135
New Jersey         130
Oregon             124
Name: count, dtype: int64

======================================================================
TOP CUSTOMER CITIES
======================================================================

City
New York City    915
Los Angeles      747
Philadelphia     537
San Francisco    510
Seattle          428
Houston          377
Chicago          314
Columbus         222
San Diego        170
Springfield      163
Dallas           157
Jacksonville     125
Detroit          115
Newark            95
Richmond          90
Jackson           82
Columbia          81
Aurora            68
Phoenix           63
Long Beach        61
Name: count, dtype: int64

======================================================================
COUNTRIES
======================================================================

Country/Region
United States    9994
Canada            200
Name: count, dtype: int64

In [41]:
# ============================================
# STEP 6: POSTAL CODE STANDARDIZATION
# ============================================

# Work on a copy
df_analysis["Postal Code Clean"] = (
    df_analysis["Postal Code"]
    .astype(str)
    .str.strip()
)

print("=" * 70)
print("POSTAL CODE ANALYSIS")
print("=" * 70)

print("Unique postal codes:",
      df_analysis["Postal Code Clean"].nunique())

print("\nSample postal codes:")

display(
    df_analysis[
        [
            "Country/Region",
            "State/Province",
            "City",
            "Postal Code",
            "Postal Code Clean"
        ]
    ]
    .drop_duplicates()
    .head(20)
)

======================================================================
POSTAL CODE ANALYSIS
======================================================================
Unique postal codes: 654

Sample postal codes:

,Country/Region,State/Province,City,Postal Code,Postal Code Clean
0,United States,Texas,Houston,77095,77095
1,United States,Illinois,Naperville,60540,60540
4,United States,Pennsylvania,Philadelphia,19143,19143
5,United States,Kentucky,Henderson,42420,42420
7,United States,Georgia,Athens,30605,30605
11,United States,California,Los Angeles,90049,90049
14,United States,Texas,Huntsville,77340,77340
16,United States,Texas,Laredo,78041,78041
18,United States,Virginia,Springfield,22153,22153
20,United States,Delaware,Dover,19901,19901
21,United States,California,San Francisco,94109,94109
22,United States,South Carolina,Mount Pleasant,29464,29464
24,United States,Ohio,Newark,43055,43055
25,United States,Louisiana,Bossier City,71111,71111
32,United States,Pennsylvania,Philadelphia,19140,19140
33,United States,Georgia,Roswell,30076,30076
34,United States,Pennsylvania,Philadelphia,19134,19134
38,United States,Oregon,Springfield,97477,97477
39,United States,Arizona,Scottsdale,85254,85254
43,United States,Arkansas,Jonesboro,72401,72401

In [231]:
# ============================================
# STEP 7: UNIQUE CUSTOMER LOCATIONS
# ============================================

customer_locations = (
    df_analysis[
        [
            "Country/Region",
            "State/Province",
            "City",
            "Postal Code Clean"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("=" * 70)
print("CUSTOMER LOCATION TABLE")
print("=" * 70)

print("Unique customer locations:", len(customer_locations))

display(customer_locations.head(20))

======================================================================
CUSTOMER LOCATION TABLE
======================================================================
Unique customer locations: 655

   Country/Region  State/Province            City Postal Code Clean
0   United States           Texas         Houston             77095
1   United States        Illinois      Naperville             60540
2   United States    Pennsylvania    Philadelphia             19143
3   United States        Kentucky       Henderson             42420
4   United States         Georgia          Athens             30605
5   United States      California     Los Angeles             90049
6   United States           Texas      Huntsville             77340
7   United States           Texas          Laredo             78041
8   United States        Virginia     Springfield             22153
9   United States        Delaware           Dover             19901
10  United States      California   San Francisco             94109
11  United States  South Carolina  Mount Pleasant             29464
12  United States            Ohio          Newark             43055
13  United States       Louisiana    Bossier City             71111
14  United States    Pennsylvania    Philadelphia             19140
15  United States         Georgia         Roswell             30076
16  United States    Pennsylvania    Philadelphia             19134
17  United States          Oregon     Springfield             97477
18  United States         Arizona      Scottsdale             85254
19  United States        Arkansas       Jonesboro             72401

In [233]:
# ============================================
# STEP 8: DATE FEATURE ENGINEERING
# ============================================

# Convert dates to datetime
df_analysis["Order Date"] = pd.to_datetime(
    df_analysis["Order Date"],
    dayfirst=True,
    errors="coerce"
)

df_analysis["Ship Date"] = pd.to_datetime(
    df_analysis["Ship Date"],
    dayfirst=True,
    errors="coerce"
)

# Calculate shipping lead time
df_analysis["Shipping Lead Time"] = (
    df_analysis["Ship Date"] - df_analysis["Order Date"]
).dt.days

# Additional time features
df_analysis["Order Year"] = df_analysis["Order Date"].dt.year
df_analysis["Order Month"] = df_analysis["Order Date"].dt.month
df_analysis["Order Quarter"] = df_analysis["Order Date"].dt.quarter
df_analysis["Order DayOfWeek"] = df_analysis["Order Date"].dt.dayofweek

print("=" * 70)
print("DATE FEATURE ENGINEERING")
print("=" * 70)

print("Invalid Order Dates:",
      df_analysis["Order Date"].isna().sum())

print("Invalid Ship Dates:",
      df_analysis["Ship Date"].isna().sum())

print("Invalid Lead Times:",
      df_analysis["Shipping Lead Time"].isna().sum())

print("\nLead Time Statistics:")

display(
    df_analysis["Shipping Lead Time"]
    .describe()
    .to_frame()
)

======================================================================
DATE FEATURE ENGINEERING
======================================================================
Invalid Order Dates: 0
Invalid Ship Dates: 0
Invalid Lead Times: 0

Lead Time Statistics:

       Shipping Lead Time
count        10194.000000
mean          1320.841868
std            262.444892
min            904.000000
25%           1271.000000
50%           1274.000000
75%           1638.000000
max           1642.000000

In [235]:
# ============================================
# STEP 9: SHIPPING MODE ANALYSIS
# ============================================

print("=" * 70)
print("SHIPPING MODE ANALYSIS")
print("=" * 70)

ship_mode_summary = (
    df_analysis.groupby("Ship Mode")
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Avg_Sales=("Sales", "mean"),
        Avg_Gross_Profit=("Gross Profit", "mean")
    )
    .round(2)
    .sort_values("Avg_Lead_Time")
)

display(ship_mode_summary)

======================================================================
SHIPPING MODE ANALYSIS
======================================================================

,Orders,Avg_Lead_Time,Median_Lead_Time,Avg_Sales,Avg_Gross_Profit
Ship Mode,,,,,
Standard Class,6120,1314.33,1274.0,13.97,9.22
Second Class,1979,1323.85,1273.0,14.08,9.25
Same Day,547,1333.44,1269.0,13.00,8.59
First Class,1548,1338.28,1272.0,13.77,9.05

In [237]:
# ============================================
# 9.2:PRODUCT SHIPPING PERFORMANCE
# ============================================

print("=" * 70)
print("PRODUCT SHIPPING PERFORMANCE")
print("=" * 70)

product_summary = (
    df_analysis.groupby("Product Name")
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Avg_Sales=("Sales", "mean"),
        Avg_Gross_Profit=("Gross Profit", "mean"),
        Total_Units=("Units", "sum")
    )
    .round(2)
    .sort_values("Avg_Lead_Time")
)

display(product_summary)

======================================================================
PRODUCT SHIPPING PERFORMANCE
======================================================================

,Orders,Avg_Lead_Time,Median_Lead_Time,Avg_Sales,Avg_Gross_Profit,Total_Units
Product Name,,,,,,
Fun Dip,3,1272.67,1272.0,4.00,1.60,8
Kazookles,96,1272.99,1273.0,12.56,0.97,371
Fizzy Lifting Drinks,6,1273.50,1274.0,13.12,7.88,21
Nerds,4,1274.00,1274.0,3.75,1.75,10
Wonka Gum,120,1306.53,1273.5,4.98,2.59,478
Wonka Bar - Fudge Mallows,1818,1314.24,1274.0,13.69,9.13,6914
Wonka Bar - Milk Chocolate,2137,1316.76,1274.0,12.57,8.16,8267
Wonka Bar -Scrumdiddlyumptious,2064,1320.64,1274.0,13.51,9.38,7743
Wonka Bar - Triple Dazzle Caramel,2015,1325.66,1274.0,14.14,9.24,7596
Wonka Bar - Nutty Crunch Surprise,1810,1328.92,1274.0,13.02,9.29,6755
Lickable Wallpaper,94,1339.14,1274.0,83.62,41.81,393
Laffy Taffy,10,1383.10,1275.0,5.37,3.35,27
SweeTARTS,10,1383.50,1274.0,6.15,2.87,41
Everlasting Gobstopper,3,1394.67,1273.0,43.33,34.67,13
Hair Toffee,4,1455.25,1455.0,19.12,14.88,17

In [239]:
# ============================================
# 9.4:FACTORY SHIPPING PERFORMANCE
# ============================================

print("=" * 70)
print("FACTORY SHIPPING PERFORMANCE")
print("=" * 70)

factory_summary = (
    df_analysis.groupby("Current Factory")
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Avg_Sales=("Sales", "mean"),
        Avg_Gross_Profit=("Gross Profit", "mean"),
        Total_Units=("Units", "sum")
    )
    .round(2)
    .sort_values("Avg_Lead_Time")
)

display(factory_summary)

======================================================================
FACTORY SHIPPING PERFORMANCE
======================================================================

,Orders,Avg_Lead_Time,Median_Lead_Time,Avg_Sales,Avg_Gross_Profit,Total_Units
Current Factory,,,,,,
The Other Factory,100,1280.28,1273.0,12.82,1.52,388
Wicked Choccy's,4152,1321.08,1274.0,13.33,8.68,15863
Lot's O' Nuts,5692,1321.23,1274.0,13.41,9.27,21412
Secret Factory,217,1321.87,1274.0,39.57,20.02,884
Sugar Shack,33,1340.03,1274.0,6.70,3.67,107

In [241]:
# ============================================
# STEP 9.5: REGIONAL SHIPPING PERFORMANCE
# ============================================

print("=" * 70)
print("REGIONAL SHIPPING PERFORMANCE")
print("=" * 70)

region_summary = (
    df_analysis.groupby("Region")
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Avg_Sales=("Sales", "mean"),
        Avg_Gross_Profit=("Gross Profit", "mean"),
        Total_Units=("Units", "sum")
    )
    .round(2)
    .sort_values("Avg_Lead_Time")
)

display(region_summary)

======================================================================
REGIONAL SHIPPING PERFORMANCE
======================================================================

,Orders,Avg_Lead_Time,Median_Lead_Time,Avg_Sales,Avg_Gross_Profit,Total_Units
Region,,,,,,
Gulf,1620,1311.37,1274.0,13.73,9.07,6209
Pacific,3253,1322.19,1274.0,14.23,9.37,12466
Atlantic,2986,1322.75,1274.0,13.80,9.03,11159
Interior,2335,1323.09,1274.0,13.72,9.11,8820

In [243]:
# ============================================
# STEP 9.6: PROFITABILITY ANALYSIS
# ============================================

print("=" * 70)
print("PROFITABILITY ANALYSIS")
print("=" * 70)

profit_summary = (
    df_analysis.groupby("Product Name")
    .agg(
        Orders=("Order ID", "count"),
        Total_Sales=("Sales", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum"),
        Total_Cost=("Cost", "sum"),
        Total_Units=("Units", "sum"),
        Avg_Gross_Profit=("Gross Profit", "mean")
    )
)

# Calculate profit margin
profit_summary["Profit_Margin_%"] = (
    profit_summary["Total_Gross_Profit"]
    / profit_summary["Total_Sales"]
    * 100
)

profit_summary = (
    profit_summary
    .round(2)
    .sort_values("Total_Gross_Profit", ascending=False)
)

display(profit_summary)

======================================================================
PROFITABILITY ANALYSIS
======================================================================

,Orders,Total_Sales,Total_Gross_Profit,Total_Cost,Total_Units,Avg_Gross_Profit,Profit_Margin_%
Product Name,,,,,,,
Wonka Bar -Scrumdiddlyumptious,2064,27874.80,19357.50,8517.30,7743,9.38,69.44
Wonka Bar - Triple Dazzle Caramel,2015,28485.00,18610.20,9874.80,7596,9.24,65.33
Wonka Bar - Milk Chocolate,2137,26867.75,17443.37,9424.38,8267,8.16,64.92
Wonka Bar - Nutty Crunch Surprise,1810,23574.95,16819.95,6755.00,6755,9.29,71.35
Wonka Bar - Fudge Mallows,1818,24890.40,16593.60,8296.80,6914,9.13,66.67
Lickable Wallpaper,94,7860.00,3930.00,3930.00,393,41.81,50.00
Wonka Gum,120,597.50,310.70,286.80,478,2.59,52.00
Everlasting Gobstopper,3,130.00,104.00,26.00,13,34.67,80.00
Kazookles,96,1205.75,92.75,1113.00,371,0.97,7.69
Hair Toffee,4,76.50,59.50,17.00,17,14.88,77.78
Fizzy Lifting Drinks,6,78.75,47.25,31.50,21,7.88,60.00
Laffy Taffy,10,53.73,33.48,20.25,27,3.35,62.31
SweeTARTS,10,61.50,28.70,32.80,41,2.87,46.67
Nerds,4,15.00,7.00,8.00,10,1.75,46.67
Fun Dip,3,12.00,4.80,7.20,8,1.60,40.00

In [245]:
# ============================================
# STEP 9.7: CORRELATION ANALYSIS
# ============================================

print("=" * 70)
print("NUMERICAL CORRELATION ANALYSIS")
print("=" * 70)

correlation_columns = [
    "Shipping Lead Time",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

correlation_matrix = (
    df_analysis[correlation_columns]
    .corr()
    .round(3)
)

display(correlation_matrix)

print("\n" + "=" * 70)
print("CORRELATION WITH SHIPPING LEAD TIME")
print("=" * 70)

lead_time_correlation = (
    correlation_matrix["Shipping Lead Time"]
    .drop("Shipping Lead Time")
    .sort_values(ascending=False)
)

display(
    lead_time_correlation.to_frame(
        name="Correlation with Shipping Lead Time"
    )
)

======================================================================
NUMERICAL CORRELATION ANALYSIS
======================================================================

                    Shipping Lead Time  Sales  Units  Gross Profit   Cost
Shipping Lead Time               1.000 -0.005 -0.007        -0.003 -0.008
Sales                           -0.005  1.000  0.729         0.976  0.959
Units                           -0.007  0.729  1.000         0.816  0.563
Gross Profit                    -0.003  0.976  0.816         1.000  0.875
Cost                            -0.008  0.959  0.563         0.875  1.000

======================================================================
CORRELATION WITH SHIPPING LEAD TIME
======================================================================

              Correlation with Shipping Lead Time
Gross Profit                               -0.003
Sales                                      -0.005
Units                                      -0.007
Cost                                       -0.008

In [247]:
# ============================================
# STEP 9.8: LEAD TIME BY SHIP MODE
# ============================================

print("=" * 70)
print("LEAD TIME BY SHIPPING MODE")
print("=" * 70)

ship_mode_analysis = (
    df_analysis.groupby("Ship Mode")
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Std_Lead_Time=("Shipping Lead Time", "std"),
        Min_Lead_Time=("Shipping Lead Time", "min"),
        Max_Lead_Time=("Shipping Lead Time", "max")
    )
    .sort_values("Avg_Lead_Time")
)

ship_mode_analysis = ship_mode_analysis.round(2)

display(ship_mode_analysis)

======================================================================
LEAD TIME BY SHIPPING MODE
======================================================================

,Orders,Avg_Lead_Time,Median_Lead_Time,Std_Lead_Time,Min_Lead_Time,Max_Lead_Time
Ship Mode,,,,,,
Standard Class,6120,1314.33,1274.0,262.40,908,1642
Second Class,1979,1323.85,1273.0,261.81,906,1640
Same Day,547,1333.44,1269.0,253.81,904,1636
First Class,1548,1338.28,1272.0,265.63,905,1638

In [249]:
# ============================================
# STEP 10.1: DATE PATTERN DIAGNOSTIC
# ============================================

print("=" * 70)
print("DATE PATTERN DIAGNOSTIC")
print("=" * 70)

print("\nOrder Date range:")
print(df_analysis["Order Date"].min())
print("to")
print(df_analysis["Order Date"].max())

print("\nShip Date range:")
print(df_analysis["Ship Date"].min())
print("to")
print(df_analysis["Ship Date"].max())

print("\nMost common lead times:")
display(
    df_analysis["Shipping Lead Time"]
    .value_counts()
    .head(15)
    .to_frame("Frequency")
)

print("\nLead time by Order Year:")

order_year_analysis = (
    df_analysis
    .groupby(df_analysis["Order Date"].dt.year)
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Min_Lead_Time=("Shipping Lead Time", "min"),
        Max_Lead_Time=("Shipping Lead Time", "max")
    )
    .round(2)
)

display(order_year_analysis)

======================================================================
DATE PATTERN DIAGNOSTIC
======================================================================

Order Date range:
2024-01-02 00:00:00
to
2025-12-31 00:00:00

Ship Date range:
2026-06-30 00:00:00
to
2030-06-28 00:00:00

Most common lead times:

                    Frequency
Shipping Lead Time
1273                     1326
1274                     1035
1639                      896
1640                      657
1275                      612
1271                      610
908                       591
909                       519
1272                      456
1637                      449
1638                      411
1641                      397
1276                      293
906                       289
1269                      258

Lead time by Order Year:

            Orders  Avg_Lead_Time  Min_Lead_Time  Max_Lead_Time
Order Date
2024          4181        1094.02            904           1277
2025          6013        1478.56           1269           1642

In [255]:
# ============================================
# STEP 10.2: ML DATASET PREPARATION
# ============================================

print("=" * 70)
print("ML DATASET PREPARATION")
print("=" * 70)

ml_df = df_analysis.copy()

# --------------------------------------------
# 1. Create date-based features
# --------------------------------------------

ml_df["Order Year"] = ml_df["Order Date"].dt.year
ml_df["Order Month"] = ml_df["Order Date"].dt.month
ml_df["Order Quarter"] = ml_df["Order Date"].dt.quarter
ml_df["Order DayOfWeek"] = ml_df["Order Date"].dt.dayofweek

# --------------------------------------------
# 2. Select ML features
# --------------------------------------------

feature_columns = [
    "Product ID",
    "Division",
    "Current Factory",
    "Region",
    "Ship Mode",
    "Order Year",
    "Order Month",
    "Order Quarter",
    "Order DayOfWeek",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit"
]

target_column = "Shipping Lead Time"

X = ml_df[feature_columns].copy()
y = ml_df[target_column].copy()

print("\nFeature matrix shape:", X.shape)
print("Target shape:", y.shape)

print("\nFeatures:")
for i, feature in enumerate(feature_columns, 1):
    print(f"{i:2}. {feature}")

print("\nTarget:")
print(target_column)

print("\nMissing values in features:")
display(X.isnull().sum().to_frame("Missing"))

print("\nMissing values in target:")
print(y.isnull().sum())

======================================================================
ML DATASET PREPARATION
======================================================================

Feature matrix shape: (10194, 13)
Target shape: (10194,)

Features:
 1. Product ID
 2. Division
 3. Current Factory
 4. Region
 5. Ship Mode
 6. Order Year
 7. Order Month
 8. Order Quarter
 9. Order DayOfWeek
10. Units
11. Sales
12. Cost
13. Gross Profit

Target:
Shipping Lead Time

Missing values in features:

                 Missing
Product ID             0
Division               0
Current Factory        0
Region                 0
Ship Mode              0
Order Year             0
Order Month            0
Order Quarter          0
Order DayOfWeek        0
Units                  0
Sales                  0
Cost                   0
Gross Profit           0

Missing values in target:
0

In [66]:
#STEP 10.3 — TRAIN/TEST SPLIT AND CATEGORICAL ENCODING

In [257]:
# ============================================
# STEP 10.3: TRAIN/TEST SPLIT + ENCODING
# ============================================

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

print("=" * 70)
print("TRAIN / TEST SPLIT AND CATEGORICAL ENCODING")
print("=" * 70)

# --------------------------------------------
# 1. Identify categorical and numerical features
# --------------------------------------------

categorical_features = [
    "Product ID",
    "Division",
    "Current Factory",
    "Region",
    "Ship Mode"
]

numerical_features = [
    "Order Year",
    "Order Month",
    "Order Quarter",
    "Order DayOfWeek",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit"
]

# --------------------------------------------
# 2. Train / Test Split
# --------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nOriginal dataset:", X.shape)
print("Training dataset:", X_train.shape)
print("Testing dataset:", X_test.shape)

# --------------------------------------------
# 3. Create preprocessing transformer
# --------------------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_features
        ),
        (
            "numerical",
            "passthrough",
            numerical_features
        )
    ]
)

# --------------------------------------------
# 4. Fit preprocessing ONLY on training data
# --------------------------------------------

X_train_encoded = preprocessor.fit_transform(X_train)

X_test_encoded = preprocessor.transform(X_test)

print("\nEncoded training shape:", X_train_encoded.shape)
print("Encoded testing shape:", X_test_encoded.shape)

print("\nEncoding completed successfully.")

======================================================================
TRAIN / TEST SPLIT AND CATEGORICAL ENCODING
======================================================================

Original dataset: (10194, 13)
Training dataset: (8155, 13)
Testing dataset: (2039, 13)

Encoded training shape: (8155, 39)
Encoded testing shape: (2039, 39)

Encoding completed successfully.

In [259]:
# ================================================================
# STEP 10.4 — LINEAR REGRESSION BASELINE MODEL
# ================================================================

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

print("=" * 70)
print("LINEAR REGRESSION BASELINE MODEL")
print("=" * 70)

# Create the Linear Regression model
linear_model = LinearRegression()

# Train the model
linear_model.fit(X_train_encoded, y_train)

print("\nModel training completed successfully.")

# Make predictions on the testing dataset
y_pred_linear = linear_model.predict(X_test_encoded)

# Calculate evaluation metrics
mae_linear = mean_absolute_error(y_test, y_pred_linear)
rmse_linear = np.sqrt(mean_squared_error(y_test, y_pred_linear))
r2_linear = r2_score(y_test, y_pred_linear)

# Display results
print("\n" + "=" * 70)
print("LINEAR REGRESSION PERFORMANCE")
print("=" * 70)

print(f"MAE  : {mae_linear:.4f}")
print(f"RMSE : {rmse_linear:.4f}")
print(f"R²   : {r2_linear:.4f}")

print("\nBaseline model evaluation completed.")

======================================================================
LINEAR REGRESSION BASELINE MODEL
======================================================================

Model training completed successfully.

======================================================================
LINEAR REGRESSION PERFORMANCE
======================================================================
MAE  : 181.4749
RMSE : 182.5624
R²   : 0.5287

Baseline model evaluation completed.

In [261]:
# ================================================================
# STEP 10.5 — RANDOM FOREST REGRESSOR
# ================================================================

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

print("=" * 70)
print("RANDOM FOREST REGRESSOR")
print("=" * 70)

# Create Random Forest model
rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_model.fit(X_train_encoded, y_train)

print("\nModel training completed successfully.")

# Make predictions
y_pred_rf = rf_model.predict(X_test_encoded)

# Calculate evaluation metrics
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

# Display results
print("\n" + "=" * 70)
print("RANDOM FOREST PERFORMANCE")
print("=" * 70)

print(f"MAE  : {mae_rf:.4f}")
print(f"RMSE : {rmse_rf:.4f}")
print(f"R²   : {r2_rf:.4f}")

print("\nRandom Forest evaluation completed.")

======================================================================
RANDOM FOREST REGRESSOR
======================================================================

Model training completed successfully.

======================================================================
RANDOM FOREST PERFORMANCE
======================================================================
MAE  : 151.5239
RMSE : 170.1499
R²   : 0.5906

Random Forest evaluation completed.

In [262]:
# ================================================================
# STEP 10.6 — GRADIENT BOOSTING REGRESSOR
# ================================================================

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

print("=" * 70)
print("GRADIENT BOOSTING REGRESSOR")
print("=" * 70)

# Create Gradient Boosting model
gb_model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)

# Train the model
gb_model.fit(X_train_encoded, y_train)

print("\nModel training completed successfully.")

# Make predictions
y_pred_gb = gb_model.predict(X_test_encoded)

# Calculate evaluation metrics
mae_gb = mean_absolute_error(y_test, y_pred_gb)
rmse_gb = np.sqrt(mean_squared_error(y_test, y_pred_gb))
r2_gb = r2_score(y_test, y_pred_gb)

# Display results
print("\n" + "=" * 70)
print("GRADIENT BOOSTING PERFORMANCE")
print("=" * 70)

print(f"MAE  : {mae_gb:.4f}")
print(f"RMSE : {rmse_gb:.4f}")
print(f"R²   : {r2_gb:.4f}")

print("\nGradient Boosting evaluation completed.")

======================================================================
GRADIENT BOOSTING REGRESSOR
======================================================================

Model training completed successfully.

======================================================================
GRADIENT BOOSTING PERFORMANCE
======================================================================
MAE  : 155.8964
RMSE : 168.4407
R²   : 0.5988

Gradient Boosting evaluation completed.

In [267]:
# ================================================================
# STEP 10.7 — MODEL COMPARISON
# ================================================================

print("=" * 70)
print("MODEL COMPARISON")
print("=" * 70)

# Create comparison table
model_comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "MAE": [
        mae_linear,
        mae_rf,
        mae_gb
    ],
    "RMSE": [
        rmse_linear,
        rmse_rf,
        rmse_gb
    ],
    "R2": [
        r2_linear,
        r2_rf,
        r2_gb
    ]
})

# Round values
model_comparison[["MAE", "RMSE", "R2"]] = (
    model_comparison[["MAE", "RMSE", "R2"]].round(4)
)

display(model_comparison)

# Identify best models for each metric
best_mae_model = model_comparison.loc[
    model_comparison["MAE"].idxmin(), "Model"
]

best_rmse_model = model_comparison.loc[
    model_comparison["RMSE"].idxmin(), "Model"
]

best_r2_model = model_comparison.loc[
    model_comparison["R2"].idxmax(), "Model"
]

print("\n" + "=" * 70)
print("BEST MODEL BY METRIC")
print("=" * 70)

print(f"Best MAE  : {best_mae_model}")
print(f"Best RMSE : {best_rmse_model}")
print(f"Best R²   : {best_r2_model}")

======================================================================
MODEL COMPARISON
======================================================================

               Model       MAE      RMSE      R2
0  Linear Regression  181.4749  182.5624  0.5287
1      Random Forest  151.5239  170.1499  0.5906
2  Gradient Boosting  155.8964  168.4407  0.5988

======================================================================
BEST MODEL BY METRIC
======================================================================
Best MAE  : Random Forest
Best RMSE : Gradient Boosting
Best R²   : Gradient Boosting

In [82]:
#Model Selection: Three regression models were evaluated to predict shipping lead time. 
#Linear Regression was used as the baseline, while Random Forest and Gradient Boosting were used as advanced ensemble models.
#Gradient Boosting achieved the lowest RMSE (168.4407) and highest R² (0.5988), indicating the strongest overall predictive performance. 
#Therefore, Gradient Boosting was selected as the final predictive model for the factory reallocation and shipping optimization system.

In [269]:
# ================================================================
# STEP 10.8 — FINAL MODEL PREDICTIONS
# ================================================================

print("=" * 70)
print("STEP 10.7 — FINAL MODEL PREDICTIONS")
print("=" * 70)

# Use the selected Gradient Boosting model
final_model = gb_model

# Generate predictions on the test dataset
y_pred_final = final_model.predict(X_test_encoded)

# Create prediction comparison table
prediction_results = pd.DataFrame({
    "Actual Shipping Lead Time": y_test.values,
    "Predicted Shipping Lead Time": y_pred_final
})

# Calculate prediction error
prediction_results["Prediction Error"] = (
    prediction_results["Actual Shipping Lead Time"]
    - prediction_results["Predicted Shipping Lead Time"]
)

prediction_results["Absolute Error"] = (
    prediction_results["Prediction Error"].abs()
)

print("\nFirst 10 predictions:")

display(prediction_results.head(10))

print("\n" + "=" * 70)
print("FINAL MODEL PERFORMANCE")
print("=" * 70)

print(f"MAE  : {mae_gb:.4f}")
print(f"RMSE : {rmse_gb:.4f}")
print(f"R²   : {r2_gb:.4f}")

print("\nPrediction generation completed successfully.")

======================================================================
STEP 10.7 — FINAL MODEL PREDICTIONS
======================================================================

First 10 predictions:

,Actual Shipping Lead Time,Predicted Shipping Lead Time,Prediction Error,Absolute Error
0,1269,1391.364280,-122.364280,122.364280
1,1272,1094.991434,177.008566,177.008566
2,1273,1349.676259,-76.676259,76.676259
3,1275,1491.514339,-216.514339,216.514339
4,1640,1517.978350,122.021650,122.021650
5,1273,1330.381097,-57.381097,57.381097
6,1273,1199.950468,73.049532,73.049532
7,1273,1166.496523,106.503477,106.503477
8,1270,1418.857159,-148.857159,148.857159
9,1641,1484.901166,156.098834,156.098834

======================================================================
FINAL MODEL PERFORMANCE
======================================================================
MAE  : 155.8964
RMSE : 168.4407
R²   : 0.5988

Prediction generation completed successfully.

In [271]:
# ================================================================
# STEP 10.9 — PREDICTION ERROR ANALYSIS
# ================================================================

print("=" * 70)
print("STEP 10.8 — PREDICTION ERROR ANALYSIS")
print("=" * 70)

# Overall error statistics
error_summary = prediction_results["Absolute Error"].describe()

print("\nPrediction Error Statistics:")
display(error_summary.to_frame(name="Absolute Error"))

# Largest prediction errors
print("\n" + "=" * 70)
print("TOP 20 LARGEST PREDICTION ERRORS")
print("=" * 70)

largest_errors = prediction_results.sort_values(
    by="Absolute Error",
    ascending=False
).head(20)

display(largest_errors)

# Percentage of predictions within different error limits
within_50 = (
    prediction_results["Absolute Error"] <= 50
).mean() * 100

within_100 = (
    prediction_results["Absolute Error"] <= 100
).mean() * 100

within_200 = (
    prediction_results["Absolute Error"] <= 200
).mean() * 100

print("\n" + "=" * 70)
print("PREDICTION ACCURACY RANGE")
print("=" * 70)

print(f"Predictions within ±50 days  : {within_50:.2f}%")
print(f"Predictions within ±100 days : {within_100:.2f}%")
print(f"Predictions within ±200 days : {within_200:.2f}%")

======================================================================
STEP 10.8 — PREDICTION ERROR ANALYSIS
======================================================================

Prediction Error Statistics:

       Absolute Error
count     2039.000000
mean       155.896367
std         63.801239
min          0.004706
25%        124.262397
50%        165.719948
75%        196.025317
max        395.229355

======================================================================
TOP 20 LARGEST PREDICTION ERRORS
======================================================================

,Actual Shipping Lead Time,Predicted Shipping Lead Time,Prediction Error,Absolute Error
1627,1272,1667.229355,-395.229355,395.229355
361,908,1278.413444,-370.413444,370.413444
1893,1273,1640.326626,-367.326626,367.326626
318,1638,1276.502534,361.497466,361.497466
2002,906,1252.293475,-346.293475,346.293475
1063,1638,1292.760389,345.239611,345.239611
1040,1273,1614.730375,-341.730375,341.730375
353,1273,938.686116,334.313884,334.313884
1500,1272,1604.688148,-332.688148,332.688148
97,908,1239.106176,-331.106176,331.106176
323,1274,946.747584,327.252416,327.252416
612,1638,1314.951574,323.048426,323.048426
387,1272,1594.131985,-322.131985,322.131985
78,909,1230.387408,-321.387408,321.387408
25,1637,1316.756714,320.243286,320.243286
1553,1273,953.249310,319.750690,319.750690
631,1639,1323.495641,315.504359,315.504359
1471,1275,960.919525,314.080475,314.080475
623,1640,1326.485570,313.514430,313.514430
1029,909,1222.290054,-313.290054,313.290054

======================================================================
PREDICTION ACCURACY RANGE
======================================================================
Predictions within ±50 days  : 9.27%
Predictions within ±100 days : 18.29%
Predictions within ±200 days : 78.08%

In [273]:
# ================================================================
# STEP 10.10 — FACTORY-LEVEL BASELINE
# ================================================================

print("=" * 70)
print("STEP 10.10 — FACTORY-LEVEL BASELINE")
print("=" * 70)

# Check whether factory mapping exists
if "Current Factory" not in df.columns:
    print("Current Factory column is missing from df.")
    print("\nAvailable columns:")
    print(df.columns.tolist())
else:
    factory_baseline = df.groupby("Current Factory").agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Avg_Sales=("Sales", "mean"),
        Avg_Gross_Profit=("Gross Profit", "mean"),
        Total_Units=("Units", "sum")
    ).reset_index()

    factory_baseline = factory_baseline.sort_values(
        "Avg_Lead_Time"
    ).reset_index(drop=True)

    factory_baseline[
        ["Avg_Lead_Time", "Median_Lead_Time",
         "Avg_Sales", "Avg_Gross_Profit"]
    ] = factory_baseline[
        ["Avg_Lead_Time", "Median_Lead_Time",
         "Avg_Sales", "Avg_Gross_Profit"]
    ].round(2)

    display(factory_baseline)

    print("\nFactory baseline analysis completed successfully.")

======================================================================
STEP 10.10 — FACTORY-LEVEL BASELINE
======================================================================
Current Factory column is missing from df.

Available columns:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost']

In [43]:
# ============================================================
# STEP 10.11 — FACTORY-LEVEL SHIPPING LEAD-TIME BASELINE
# ============================================================
import pandas as pd
import numpy as np
print("Current Factory exists:",
      "Current Factory" in df_analysis.columns)

print(df_analysis["Current Factory"].value_counts())
print("=" * 70)
print("STEP 10.11 — FACTORY-LEVEL SHIPPING LEAD-TIME BASELINE")
print("=" * 70)

# Work from df_analysis because Current Factory was created there
df_analysis["Order Date"] = pd.to_datetime(
    df_analysis["Order Date"],
    dayfirst=True
)

df_analysis["Ship Date"] = pd.to_datetime(
    df_analysis["Ship Date"],
    dayfirst=True
)

# Recalculate shipping lead time
df_analysis["Shipping Lead Time"] = (
    df_analysis["Ship Date"] - df_analysis["Order Date"]
).dt.days

# Check for invalid lead times
print("\nLead-time validation:")
print(
    "Negative lead-time records:",
    (df_analysis["Shipping Lead Time"] < 0).sum()
)

print(
    "Missing lead-time records:",
    df_analysis["Shipping Lead Time"].isna().sum()
)

# Factory-level baseline
factory_baseline = (
    df_analysis
    .groupby("Current Factory")
    .agg(
        Average_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Min_Lead_Time=("Shipping Lead Time", "min"),
        Max_Lead_Time=("Shipping Lead Time", "max"),
        Records=("Shipping Lead Time", "count")
    )
    .reset_index()
    .sort_values("Average_Lead_Time", ascending=False)
)

print("\n" + "=" * 70)
print("FACTORY-LEVEL SHIPPING BASELINE")
print("=" * 70)

display(factory_baseline)

print("\nStep 10.11 completed successfully.")

Current Factory exists: True
Current Factory
Lot's O' Nuts        5692
Wicked Choccy's      4152
Secret Factory        217
The Other Factory     100
Sugar Shack            33
Name: count, dtype: int64
======================================================================
STEP 10.11 — FACTORY-LEVEL SHIPPING LEAD-TIME BASELINE
======================================================================

Lead-time validation:
Negative lead-time records: 0
Missing lead-time records: 0

======================================================================
FACTORY-LEVEL SHIPPING BASELINE
======================================================================

,Current Factory,Average_Lead_Time,Median_Lead_Time,Min_Lead_Time,Max_Lead_Time,Records
2,Sugar Shack,1340.030303,1274.0,907,1642,33
1,Secret Factory,1321.870968,1274.0,904,1642,217
0,Lot's O' Nuts,1321.228742,1274.0,904,1642,5692
4,Wicked Choccy's,1321.082129,1274.0,904,1642,4152
3,The Other Factory,1280.280000,1273.0,904,1641,100

Step 10.11 completed successfully.

In [53]:
# ================================================================
# STEP 10.12 — FACTORY OPTIMIZATION / PRODUCT REALLOCATION
# ================================================================

print("=" * 70)
print("STEP 10.12 — FACTORY OPTIMIZATION / PRODUCT REALLOCATION")
print("=" * 70)

# Use df_analysis because it contains:
# - Current Factory
# - Shipping Lead Time

# Product-level current performance
product_factory_analysis = (
    df_analysis
    .groupby(
        ["Product ID", "Product Name", "Current Factory"]
    )
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Avg_Sales=("Sales", "mean"),
        Avg_Gross_Profit=("Gross Profit", "mean"),
        Total_Units=("Units", "sum")
    )
    .reset_index()
)

# Sort by current lead time
product_factory_analysis = (
    product_factory_analysis
    .sort_values("Avg_Lead_Time", ascending=False)
    .reset_index(drop=True)
)

# Round numeric results
product_factory_analysis[
    [
        "Avg_Lead_Time",
        "Avg_Sales",
        "Avg_Gross_Profit"
    ]
] = product_factory_analysis[
    [
        "Avg_Lead_Time",
        "Avg_Sales",
        "Avg_Gross_Profit"
    ]
].round(2)

print("\n" + "=" * 70)
print("PRODUCT-LEVEL FACTORY SHIPPING PERFORMANCE")
print("=" * 70)

display(product_factory_analysis)

print("\n" + "=" * 70)
print("PRODUCT-LEVEL SUMMARY")
print("=" * 70)

print(
    "Products evaluated:",
    product_factory_analysis["Product Name"].nunique()
)

print(
    "Factories represented:",
    product_factory_analysis["Current Factory"].nunique()
)

print("\nStep 10.12 completed successfully.")

======================================================================
STEP 10.12 — FACTORY OPTIMIZATION / PRODUCT REALLOCATION
======================================================================

======================================================================
PRODUCT-LEVEL FACTORY SHIPPING PERFORMANCE
======================================================================

,Product ID,Product Name,Current Factory,Orders,Avg_Lead_Time,Avg_Sales,Avg_Gross_Profit,Total_Units
0,SUG-HAI-55000,Hair Toffee,The Other Factory,4,1455.25,19.12,14.88,17
1,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,3,1394.67,43.33,34.67,13
2,SUG-SWE-91000,SweeTARTS,Sugar Shack,10,1383.50,6.15,2.87,41
3,SUG-LAF-25000,Laffy Taffy,Sugar Shack,10,1383.10,5.37,3.35,27
4,OTH-LIC-15000,Lickable Wallpaper,Secret Factory,94,1339.14,83.62,41.81,393
5,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,1810,1328.92,13.02,9.29,6755
6,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,2015,1325.66,14.14,9.24,7596
7,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,2064,1320.64,13.51,9.38,7743
8,CHO-MIL-31000,Wonka Bar - Milk Chocolate,Wicked Choccy's,2137,1316.76,12.57,8.16,8267
9,CHO-FUD-51000,Wonka Bar - Fudge Mallows,Lot's O' Nuts,1818,1314.24,13.69,9.13,6914
10,OTH-GUM-21000,Wonka Gum,Secret Factory,120,1306.53,4.98,2.59,478
11,SUG-NER-92000,Nerds,Sugar Shack,4,1274.00,3.75,1.75,10
12,OTH-FIZ-56000,Fizzy Lifting Drinks,Sugar Shack,6,1273.50,13.12,7.88,21
13,OTH-KAZ-38000,Kazookles,The Other Factory,96,1272.99,12.56,0.97,371
14,SUG-FUN-75000,Fun Dip,Sugar Shack,3,1272.67,4.00,1.60,8

======================================================================
PRODUCT-LEVEL SUMMARY
======================================================================
Products evaluated: 15
Factories represented: 5

Step 10.12 completed successfully.

In [19]:
# ================================================================
# STEP 10.13 — REALLOCATION CANDIDATE IDENTIFICATION
# ================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 10.13 — REALLOCATION CANDIDATE IDENTIFICATION")
print("=" * 70)

# ------------------------------------------------
# 1. Make sure df_analysis exists
# ------------------------------------------------

if "df_analysis" not in globals():
    raise NameError(
        "df_analysis is not defined. "
        "Please run the earlier data-preparation cells first, "
        "especially the cell that creates df_analysis and Current Factory."
    )

# ------------------------------------------------
# 2. Make sure Shipping Lead Time exists
# ------------------------------------------------

if "Shipping Lead Time" not in df_analysis.columns:

    df_analysis["Order Date"] = pd.to_datetime(
        df_analysis["Order Date"],
        dayfirst=True,
        errors="coerce"
    )

    df_analysis["Ship Date"] = pd.to_datetime(
        df_analysis["Ship Date"],
        dayfirst=True,
        errors="coerce"
    )

    df_analysis["Shipping Lead Time"] = (
        df_analysis["Ship Date"]
        - df_analysis["Order Date"]
    ).dt.days

# ------------------------------------------------
# 3. Validate required columns
# ------------------------------------------------

required_columns = [
    "Product ID",
    "Product Name",
    "Current Factory",
    "Order ID",
    "Shipping Lead Time",
    "Sales",
    "Gross Profit",
    "Units"
]

missing_columns = [
    col for col in required_columns
    if col not in df_analysis.columns
]

if missing_columns:
    raise KeyError(
        f"Missing required columns: {missing_columns}"
    )

# ------------------------------------------------
# 4. Calculate overall shipping lead-time baseline
# ------------------------------------------------

overall_avg_lead_time = (
    df_analysis["Shipping Lead Time"].mean()
)

print(
    f"\nOverall Average Lead Time: "
    f"{overall_avg_lead_time:.2f} days"
)

# ------------------------------------------------
# 5. Calculate product-level shipping performance
# ------------------------------------------------

product_performance = (
    df_analysis
    .groupby(
        [
            "Product ID",
            "Product Name",
            "Current Factory"
        ]
    )
    .agg(
        Orders=("Order ID", "count"),
        Avg_Lead_Time=("Shipping Lead Time", "mean"),
        Avg_Sales=("Sales", "mean"),
        Avg_Gross_Profit=("Gross Profit", "mean"),
        Total_Units=("Units", "sum")
    )
    .reset_index()
)

# ------------------------------------------------
# 6. Identify products above overall average
# ------------------------------------------------

reallocation_candidates = (
    product_performance[
        product_performance["Avg_Lead_Time"]
        > overall_avg_lead_time
    ]
    .copy()
)

# ------------------------------------------------
# 7. Calculate excess lead time
# ------------------------------------------------

reallocation_candidates["Excess_Lead_Time"] = (
    reallocation_candidates["Avg_Lead_Time"]
    - overall_avg_lead_time
)

# ------------------------------------------------
# 8. Sort by greatest excess lead time
# ------------------------------------------------

reallocation_candidates = (
    reallocation_candidates
    .sort_values(
        "Excess_Lead_Time",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------
# 9. Round numerical values
# ------------------------------------------------

numeric_columns = [
    "Avg_Lead_Time",
    "Avg_Sales",
    "Avg_Gross_Profit",
    "Excess_Lead_Time"
]

reallocation_candidates[numeric_columns] = (
    reallocation_candidates[numeric_columns]
    .round(2)
)

# ------------------------------------------------
# 10. Display candidates
# ------------------------------------------------

print("\n" + "=" * 70)
print("REALLOCATION CANDIDATES")
print("=" * 70)

display(reallocation_candidates)

# ------------------------------------------------
# 11. Candidate summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("CANDIDATE SUMMARY")
print("=" * 70)

print(
    "Products identified:",
    reallocation_candidates["Product Name"].nunique()
)

if not reallocation_candidates.empty:

    print(
        "Average candidate lead time:",
        round(
            reallocation_candidates["Avg_Lead_Time"].mean(),
            2
        )
    )

    print(
        "Average excess lead time:",
        round(
            reallocation_candidates["Excess_Lead_Time"].mean(),
            2
        )
    )

else:
    print("No products have above-average lead time.")

print("\nStep 10.13 completed successfully.")

======================================================================
STEP 10.13 — REALLOCATION CANDIDATE IDENTIFICATION
======================================================================

Overall Average Lead Time: 1320.84 days

======================================================================
REALLOCATION CANDIDATES
======================================================================

,Product ID,Product Name,Current Factory,Orders,Avg_Lead_Time,Avg_Sales,Avg_Gross_Profit,Total_Units,Excess_Lead_Time
0,SUG-HAI-55000,Hair Toffee,The Other Factory,4,1455.25,19.12,14.88,17,134.41
1,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,3,1394.67,43.33,34.67,13,73.82
2,SUG-SWE-91000,SweeTARTS,Sugar Shack,10,1383.50,6.15,2.87,41,62.66
3,SUG-LAF-25000,Laffy Taffy,Sugar Shack,10,1383.10,5.37,3.35,27,62.26
4,OTH-LIC-15000,Lickable Wallpaper,Secret Factory,94,1339.14,83.62,41.81,393,18.30
5,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,1810,1328.92,13.02,9.29,6755,8.07
6,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,2015,1325.66,14.14,9.24,7596,4.82

======================================================================
CANDIDATE SUMMARY
======================================================================
Products identified: 7
Average candidate lead time: 1372.89
Average excess lead time: 52.05

Step 10.13 completed successfully.

In [23]:
# ================================================================
# STEP 10.14 — ML-BASED FACTORY REALLOCATION SIMULATION
# ================================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import GradientBoostingRegressor

print("=" * 70)
print("STEP 10.14 — ML-BASED FACTORY REALLOCATION SIMULATION")
print("=" * 70)

# ================================================================
# PART A — REBUILD REQUIRED ML OBJECTS IF THEY ARE MISSING
# ================================================================

print("\nChecking required ML objects...")

# ------------------------------------------------
# 1. Feature definitions
# ------------------------------------------------

feature_columns = [
    "Product ID",
    "Division",
    "Current Factory",
    "Region",
    "Ship Mode",
    "Order Year",
    "Order Month",
    "Order Quarter",
    "Order DayOfWeek",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit"
]

target_column = "Shipping Lead Time"

# Make sure date-based features exist
df_analysis["Order Year"] = (
    df_analysis["Order Date"].dt.year
)

df_analysis["Order Month"] = (
    df_analysis["Order Date"].dt.month
)

df_analysis["Order Quarter"] = (
    df_analysis["Order Date"].dt.quarter
)

df_analysis["Order DayOfWeek"] = (
    df_analysis["Order Date"].dt.dayofweek
)

# ------------------------------------------------
# 2. Create X and y
# ------------------------------------------------

X = df_analysis[feature_columns].copy()
y = df_analysis[target_column].copy()

# ------------------------------------------------
# 3. Identify categorical/numerical features
# ------------------------------------------------

categorical_features = [
    "Product ID",
    "Division",
    "Current Factory",
    "Region",
    "Ship Mode"
]

numerical_features = [
    "Order Year",
    "Order Month",
    "Order Quarter",
    "Order DayOfWeek",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit"
]

# ------------------------------------------------
# 4. Train/test split
# ------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# ------------------------------------------------
# 5. Recreate preprocessing
# ------------------------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_features
        ),
        (
            "numerical",
            "passthrough",
            numerical_features
        )
    ]
)

X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# ------------------------------------------------
# 6. Recreate the selected Gradient Boosting model
# ------------------------------------------------

gb_model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)

gb_model.fit(
    X_train_encoded,
    y_train
)

print("ML objects rebuilt successfully.")

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Encoded features:", X_train_encoded.shape[1])

# ================================================================
# PART B — FACTORY REALLOCATION SIMULATION
# ================================================================

# ------------------------------------------------
# 7. Available factories
# ------------------------------------------------

available_factories = sorted(
    df_analysis["Current Factory"]
    .dropna()
    .unique()
    .tolist()
)

print("\nAvailable factories:")
for factory in available_factories:
    print(" -", factory)

# ------------------------------------------------
# 8. Candidate products from Step 10.13
# ------------------------------------------------

candidate_product_ids = (
    reallocation_candidates["Product ID"]
    .unique()
    .tolist()
)

print(
    "\nCandidate products:",
    len(candidate_product_ids)
)

# ------------------------------------------------
# 9. Simulate each candidate at every alternative
#    factory
# ------------------------------------------------

ml_reallocation_results = []

for product_id in candidate_product_ids:

    product_records = df_analysis[
        df_analysis["Product ID"] == product_id
    ].copy()

    if product_records.empty:
        continue

    product_name = product_records[
        "Product Name"
    ].iloc[0]

    current_factory = product_records[
        "Current Factory"
    ].iloc[0]

    # Actual current lead time
    actual_current_lead_time = (
        product_records[
            "Shipping Lead Time"
        ].mean()
    )

    # ------------------------------------------------
    # Current-factory model prediction
    # ------------------------------------------------

    current_scenario = product_records.copy()

    current_scenario["Current Factory"] = (
        current_factory
    )

    X_current = current_scenario[
        feature_columns
    ].copy()

    X_current_encoded = (
        preprocessor.transform(X_current)
    )

    current_model_prediction = (
        gb_model
        .predict(X_current_encoded)
        .mean()
    )

    # ------------------------------------------------
    # Alternative factory scenarios
    # ------------------------------------------------

    for alternative_factory in available_factories:

        if alternative_factory == current_factory:
            continue

        scenario = product_records.copy()

        # Change ONLY the hypothetical factory
        scenario["Current Factory"] = (
            alternative_factory
        )

        X_scenario = scenario[
            feature_columns
        ].copy()

        X_scenario_encoded = (
            preprocessor.transform(X_scenario)
        )

        predicted_new_lead_time = (
            gb_model
            .predict(X_scenario_encoded)
            .mean()
        )

        # Model-based improvement
        predicted_reduction = (
            current_model_prediction
            - predicted_new_lead_time
        )

        predicted_improvement_pct = (
            predicted_reduction
            / current_model_prediction
            * 100
            if current_model_prediction != 0
            else 0
        )

        ml_reallocation_results.append({
            "Product ID": product_id,
            "Product Name": product_name,
            "Current Factory": current_factory,
            "Alternative Factory": alternative_factory,
            "Actual Current Lead Time":
                actual_current_lead_time,
            "Current Model Predicted Lead Time":
                current_model_prediction,
            "Alternative Predicted Lead Time":
                predicted_new_lead_time,
            "Predicted Lead Time Reduction":
                predicted_reduction,
            "Predicted Improvement %":
                predicted_improvement_pct,
            "Orders":
                len(product_records),
            "Total Units":
                product_records["Units"].sum(),
            "Total Sales":
                product_records["Sales"].sum(),
            "Total Gross Profit":
                product_records["Gross Profit"].sum()
        })

# ------------------------------------------------
# 10. Create scenario dataframe
# ------------------------------------------------

ml_reallocation_simulation = pd.DataFrame(
    ml_reallocation_results
)

# ------------------------------------------------
# 11. Round numerical columns
# ------------------------------------------------

numeric_columns = [
    "Actual Current Lead Time",
    "Current Model Predicted Lead Time",
    "Alternative Predicted Lead Time",
    "Predicted Lead Time Reduction",
    "Predicted Improvement %",
    "Total Sales",
    "Total Gross Profit"
]

ml_reallocation_simulation[
    numeric_columns
] = (
    ml_reallocation_simulation[
        numeric_columns
    ].round(2)
)

# ------------------------------------------------
# 12. Keep beneficial scenarios
# ------------------------------------------------

beneficial_ml_reallocations = (
    ml_reallocation_simulation[
        ml_reallocation_simulation[
            "Predicted Lead Time Reduction"
        ] > 0
    ]
    .copy()
)

# ------------------------------------------------
# 13. Best alternative factory for each product
# ------------------------------------------------

best_ml_reallocations = (
    beneficial_ml_reallocations
    .sort_values(
        [
            "Product ID",
            "Predicted Lead Time Reduction"
        ],
        ascending=[True, False]
    )
    .drop_duplicates(
        subset=["Product ID"],
        keep="first"
    )
    .sort_values(
        "Predicted Lead Time Reduction",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------
# 14. Display all scenarios
# ------------------------------------------------

print("\n" + "=" * 70)
print("ML FACTORY SCENARIO PREDICTIONS")
print("=" * 70)

display(
    ml_reallocation_simulation
)

# ------------------------------------------------
# 15. Display best recommendations
# ------------------------------------------------

print("\n" + "=" * 70)
print("BEST ML-PREDICTED FACTORY ALTERNATIVES")
print("=" * 70)

display(
    best_ml_reallocations[
        [
            "Product ID",
            "Product Name",
            "Current Factory",
            "Alternative Factory",
            "Actual Current Lead Time",
            "Current Model Predicted Lead Time",
            "Alternative Predicted Lead Time",
            "Predicted Lead Time Reduction",
            "Predicted Improvement %",
            "Orders",
            "Total Units",
            "Total Sales",
            "Total Gross Profit"
        ]
    ]
)

# ------------------------------------------------
# 16. Summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("ML REALLOCATION SUMMARY")
print("=" * 70)

print(
    "Candidate products evaluated:",
    len(candidate_product_ids)
)

print(
    "Products with beneficial ML-predicted alternative:",
    best_ml_reallocations[
        "Product ID"
    ].nunique()
)

if not best_ml_reallocations.empty:

    print(
        "Average predicted lead-time reduction:",
        round(
            best_ml_reallocations[
                "Predicted Lead Time Reduction"
            ].mean(),
            2
        ),
        "days"
    )

    print(
        "Average predicted improvement:",
        round(
            best_ml_reallocations[
                "Predicted Improvement %"
            ].mean(),
            2
        ),
        "%"
    )

print("\nStep 10.14 completed successfully.")

======================================================================
STEP 10.14 — ML-BASED FACTORY REALLOCATION SIMULATION
======================================================================

Checking required ML objects...
ML objects rebuilt successfully.
Training rows: 8155
Testing rows: 2039
Encoded features: 39

Available factories:
 - Lot's O' Nuts
 - Secret Factory
 - Sugar Shack
 - The Other Factory
 - Wicked Choccy's

Candidate products: 7

======================================================================
ML FACTORY SCENARIO PREDICTIONS
======================================================================

,Product ID,Product Name,Current Factory,Alternative Factory,Actual Current Lead Time,Current Model Predicted Lead Time,Alternative Predicted Lead Time,Predicted Lead Time Reduction,Predicted Improvement %,Orders,Total Units,Total Sales,Total Gross Profit
0,SUG-HAI-55000,Hair Toffee,The Other Factory,Lot's O' Nuts,1455.25,1473.37,1473.69,-0.32,-0.02,4,17,76.50,59.50
1,SUG-HAI-55000,Hair Toffee,The Other Factory,Secret Factory,1455.25,1473.37,1473.37,0.00,0.00,4,17,76.50,59.50
2,SUG-HAI-55000,Hair Toffee,The Other Factory,Sugar Shack,1455.25,1473.37,1473.37,0.00,0.00,4,17,76.50,59.50
3,SUG-HAI-55000,Hair Toffee,The Other Factory,Wicked Choccy's,1455.25,1473.37,1473.37,0.00,0.00,4,17,76.50,59.50
4,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,Lot's O' Nuts,1394.67,1414.00,1430.08,-16.08,-1.14,3,13,130.00,104.00
5,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,Sugar Shack,1394.67,1414.00,1397.22,16.78,1.19,3,13,130.00,104.00
6,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,The Other Factory,1394.67,1414.00,1414.00,0.00,0.00,3,13,130.00,104.00
7,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,Wicked Choccy's,1394.67,1414.00,1414.00,0.00,0.00,3,13,130.00,104.00
8,SUG-SWE-91000,SweeTARTS,Sugar Shack,Lot's O' Nuts,1383.50,1331.03,1335.24,-4.21,-0.32,10,41,61.50,28.70
9,SUG-SWE-91000,SweeTARTS,Sugar Shack,Secret Factory,1383.50,1331.03,1317.68,13.35,1.00,10,41,61.50,28.70
10,SUG-SWE-91000,SweeTARTS,Sugar Shack,The Other Factory,1383.50,1331.03,1335.56,-4.52,-0.34,10,41,61.50,28.70
11,SUG-SWE-91000,SweeTARTS,Sugar Shack,Wicked Choccy's,1383.50,1331.03,1335.94,-4.90,-0.37,10,41,61.50,28.70
12,SUG-LAF-25000,Laffy Taffy,Sugar Shack,Lot's O' Nuts,1383.10,1369.18,1369.18,0.00,0.00,10,27,53.73,33.48
13,SUG-LAF-25000,Laffy Taffy,Sugar Shack,Secret Factory,1383.10,1369.18,1352.79,16.39,1.20,10,27,53.73,33.48
14,SUG-LAF-25000,Laffy Taffy,Sugar Shack,The Other Factory,1383.10,1369.18,1369.18,0.00,0.00,10,27,53.73,33.48
15,SUG-LAF-25000,Laffy Taffy,Sugar Shack,Wicked Choccy's,1383.10,1369.18,1369.62,-0.44,-0.03,10,27,53.73,33.48
16,OTH-LIC-15000,Lickable Wallpaper,Secret Factory,Lot's O' Nuts,1339.14,1346.56,1370.26,-23.70,-1.76,94,393,7860.00,3930.00
17,OTH-LIC-15000,Lickable Wallpaper,Secret Factory,Sugar Shack,1339.14,1346.56,1352.18,-5.63,-0.42,94,393,7860.00,3930.00
18,OTH-LIC-15000,Lickable Wallpaper,Secret Factory,The Other Factory,1339.14,1346.56,1369.85,-23.30,-1.73,94,393,7860.00,3930.00
19,OTH-LIC-15000,Lickable Wallpaper,Secret Factory,Wicked Choccy's,1339.14,1346.56,1370.11,-23.55,-1.75,94,393,7860.00,3930.00
20,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Secret Factory,1328.92,1328.82,1323.75,5.07,0.38,1810,6755,23574.95,16819.95
21,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Sugar Shack,1328.92,1328.82,1323.21,5.61,0.42,1810,6755,23574.95,16819.95
22,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,The Other Factory,1328.92,1328.82,1328.56,0.26,0.02,1810,6755,23574.95,16819.95
23,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Wicked Choccy's,1328.92,1328.82,1328.76,0.06,0.00,1810,6755,23574.95,16819.95
24,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Lot's O' Nuts,1325.66,1324.99,1324.86,0.13,0.01,2015,7596,28485.00,18610.20
25,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Secret Factory,1325.66,1324.99,1320.31,4.68,0.35,2015,7596,28485.00,18610.20
26,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Sugar Shack,1325.66,1324.99,1316.98,8.01,0.60,2015,7596,28485.00,18610.20
27,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,The Other Factory,1325.66,1324.99,1324.70,0.29,0.02,2015,7596,28485.00,18610.20

======================================================================
BEST ML-PREDICTED FACTORY ALTERNATIVES
======================================================================

,Product ID,Product Name,Current Factory,Alternative Factory,Actual Current Lead Time,Current Model Predicted Lead Time,Alternative Predicted Lead Time,Predicted Lead Time Reduction,Predicted Improvement %,Orders,Total Units,Total Sales,Total Gross Profit
0,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,Sugar Shack,1394.67,1414.00,1397.22,16.78,1.19,3,13,130.00,104.00
1,SUG-LAF-25000,Laffy Taffy,Sugar Shack,Secret Factory,1383.10,1369.18,1352.79,16.39,1.20,10,27,53.73,33.48
2,SUG-SWE-91000,SweeTARTS,Sugar Shack,Secret Factory,1383.50,1331.03,1317.68,13.35,1.00,10,41,61.50,28.70
3,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Sugar Shack,1325.66,1324.99,1316.98,8.01,0.60,2015,7596,28485.00,18610.20
4,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Sugar Shack,1328.92,1328.82,1323.21,5.61,0.42,1810,6755,23574.95,16819.95

======================================================================
ML REALLOCATION SUMMARY
======================================================================
Candidate products evaluated: 7
Products with beneficial ML-predicted alternative: 5
Average predicted lead-time reduction: 12.03 days
Average predicted improvement: 0.88 %

Step 10.14 completed successfully.

In [25]:
# ================================================================
# STEP 10.15 — SCENARIO CONFIDENCE & RISK SCORE
# ================================================================

print("=" * 70)
print("STEP 10.15 — SCENARIO CONFIDENCE & RISK SCORE")
print("=" * 70)

# ------------------------------------------------
# 1. Start with the best ML recommendations
# ------------------------------------------------

scenario_risk = best_ml_reallocations.copy()

# ------------------------------------------------
# 2. Sample-size confidence
# ------------------------------------------------
# More historical orders for a product = stronger evidence.
# We cap the contribution at 100 orders.

scenario_risk["Sample_Confidence"] = (
    scenario_risk["Orders"].clip(upper=100) / 100
)

# ------------------------------------------------
# 3. Improvement confidence
# ------------------------------------------------
# Larger predicted improvement gives stronger benefit.

scenario_risk["Improvement_Score"] = (
    scenario_risk["Predicted Improvement %"]
    .clip(lower=0)
    .clip(upper=10)
    / 10
)

# ------------------------------------------------
# 4. Scenario change risk
# ------------------------------------------------
# Large difference between current model prediction
# and alternative prediction means a larger counterfactual change.

scenario_risk["Scenario_Change_%"] = (
    (
        scenario_risk["Alternative Predicted Lead Time"]
        - scenario_risk["Current Model Predicted Lead Time"]
    ).abs()
    / scenario_risk["Current Model Predicted Lead Time"]
    * 100
)

# ------------------------------------------------
# 5. Convert scenario change to risk score
# ------------------------------------------------

scenario_risk["Change_Risk"] = (
    scenario_risk["Scenario_Change_%"]
    .clip(lower=0)
    .clip(upper=10)
    / 10
)

# ------------------------------------------------
# 6. Overall confidence score
# ------------------------------------------------
# Higher is better.

scenario_risk["Confidence Score"] = (
    0.50 * scenario_risk["Sample_Confidence"]
    + 0.30 * scenario_risk["Improvement_Score"]
    + 0.20 * (1 - scenario_risk["Change_Risk"])
) * 100

scenario_risk["Confidence Score"] = (
    scenario_risk["Confidence Score"]
    .clip(lower=0, upper=100)
    .round(2)
)

# ------------------------------------------------
# 7. Risk classification
# ------------------------------------------------

def classify_risk(score):
    if score >= 70:
        return "Low Risk"
    elif score >= 40:
        return "Medium Risk"
    else:
        return "High Risk"

scenario_risk["Risk Level"] = (
    scenario_risk["Confidence Score"]
    .apply(classify_risk)
)

# ------------------------------------------------
# 8. Decision recommendation
# ------------------------------------------------

def recommendation(confidence, improvement):
    if confidence >= 70 and improvement > 0:
        return "Recommended"
    elif confidence >= 40 and improvement > 0:
        return "Review Before Reallocation"
    else:
        return "Do Not Reallocate"

scenario_risk["Recommendation"] = scenario_risk.apply(
    lambda row: recommendation(
        row["Confidence Score"],
        row["Predicted Lead Time Reduction"]
    ),
    axis=1
)

# ------------------------------------------------
# 9. Display results
# ------------------------------------------------

print("\n" + "=" * 70)
print("SCENARIO CONFIDENCE & RISK RESULTS")
print("=" * 70)

display(
    scenario_risk[
        [
            "Product ID",
            "Product Name",
            "Current Factory",
            "Alternative Factory",
            "Orders",
            "Predicted Lead Time Reduction",
            "Predicted Improvement %",
            "Scenario_Change_%",
            "Confidence Score",
            "Risk Level",
            "Recommendation"
        ]
    ]
    .sort_values(
        "Confidence Score",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------
# 10. Summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("RISK SUMMARY")
print("=" * 70)

print(
    "Low-risk recommendations:",
    (scenario_risk["Risk Level"] == "Low Risk").sum()
)

print(
    "Medium-risk recommendations:",
    (scenario_risk["Risk Level"] == "Medium Risk").sum()
)

print(
    "High-risk recommendations:",
    (scenario_risk["Risk Level"] == "High Risk").sum()
)

print(
    "Recommended:",
    (scenario_risk["Recommendation"] == "Recommended").sum()
)

print(
    "Review Before Reallocation:",
    (scenario_risk["Recommendation"] == "Review Before Reallocation").sum()
)

print(
    "Do Not Reallocate:",
    (scenario_risk["Recommendation"] == "Do Not Reallocate").sum()
)

print("\nStep 10.15 completed successfully.")

======================================================================
STEP 10.15 — SCENARIO CONFIDENCE & RISK SCORE
======================================================================

======================================================================
SCENARIO CONFIDENCE & RISK RESULTS
======================================================================

,Product ID,Product Name,Current Factory,Alternative Factory,Orders,Predicted Lead Time Reduction,Predicted Improvement %,Scenario_Change_%,Confidence Score,Risk Level,Recommendation
0,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Sugar Shack,2015,8.01,0.60,0.604533,70.59,Low Risk,Recommended
1,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Sugar Shack,1810,5.61,0.42,0.422179,70.42,Low Risk,Recommended
2,SUG-LAF-25000,Laffy Taffy,Sugar Shack,Secret Factory,10,16.39,1.20,1.197067,26.21,High Risk,Do Not Reallocate
3,SUG-SWE-91000,SweeTARTS,Sugar Shack,Secret Factory,10,13.35,1.00,1.002983,25.99,High Risk,Do Not Reallocate
4,SUG-EVE-47000,Everlasting Gobstopper,Secret Factory,Sugar Shack,3,16.78,1.19,1.186704,22.70,High Risk,Do Not Reallocate

======================================================================
RISK SUMMARY
======================================================================
Low-risk recommendations: 2
Medium-risk recommendations: 0
High-risk recommendations: 3
Recommended: 2
Review Before Reallocation: 0
Do Not Reallocate: 3

Step 10.15 completed successfully.

In [27]:
# ================================================================
# STEP 10.16 — PROFIT IMPACT ANALYSIS
# ================================================================

print("=" * 70)
print("STEP 10.16 — PROFIT IMPACT ANALYSIS")
print("=" * 70)

# ------------------------------------------------
# 1. Keep only approved recommendations
# ------------------------------------------------

approved_recommendations = scenario_risk[
    scenario_risk["Recommendation"] == "Recommended"
].copy()

# ------------------------------------------------
# 2. Calculate profit metrics
# ------------------------------------------------

approved_recommendations["Profit_Margin_%"] = (
    approved_recommendations["Total Gross Profit"]
    / approved_recommendations["Total Sales"]
    * 100
)

# ------------------------------------------------
# 3. Shipping improvement per unit
# ------------------------------------------------

approved_recommendations["Days_Saved_Per_Unit"] = (
    approved_recommendations[
        "Predicted Lead Time Reduction"
    ]
)

# ------------------------------------------------
# 4. Estimate aggregate lead-time benefit
# ------------------------------------------------

approved_recommendations["Estimated Total Days Saved"] = (
    approved_recommendations[
        "Predicted Lead Time Reduction"
    ]
    * approved_recommendations["Total Units"]
)

# ------------------------------------------------
# 5. Classify financial importance
# ------------------------------------------------

def classify_profit_impact(profit):
    if profit >= 10000:
        return "High"
    elif profit >= 1000:
        return "Medium"
    else:
        return "Low"

approved_recommendations["Profit Impact"] = (
    approved_recommendations[
        "Total Gross Profit"
    ]
    .apply(classify_profit_impact)
)

# ------------------------------------------------
# 6. Create final financial view
# ------------------------------------------------

profit_impact_table = approved_recommendations[
    [
        "Product ID",
        "Product Name",
        "Current Factory",
        "Alternative Factory",
        "Orders",
        "Total Units",
        "Total Sales",
        "Total Gross Profit",
        "Profit_Margin_%",
        "Predicted Lead Time Reduction",
        "Predicted Improvement %",
        "Estimated Total Days Saved",
        "Confidence Score",
        "Risk Level",
        "Profit Impact",
        "Recommendation"
    ]
].copy()

# Round numeric columns
numeric_columns = [
    "Total Sales",
    "Total Gross Profit",
    "Profit_Margin_%",
    "Predicted Lead Time Reduction",
    "Predicted Improvement %",
    "Estimated Total Days Saved",
    "Confidence Score"
]

profit_impact_table[numeric_columns] = (
    profit_impact_table[numeric_columns].round(2)
)

# ------------------------------------------------
# 7. Display results
# ------------------------------------------------

print("\n" + "=" * 70)
print("APPROVED REALLOCATIONS — PROFIT IMPACT")
print("=" * 70)

display(
    profit_impact_table
)

# ------------------------------------------------
# 8. Overall financial summary
# ------------------------------------------------

total_profit_exposure = (
    profit_impact_table["Total Gross Profit"].sum()
)

total_sales_exposure = (
    profit_impact_table["Total Sales"].sum()
)

total_days_saved = (
    profit_impact_table["Estimated Total Days Saved"].sum()
)

weighted_profit_margin = (
    total_profit_exposure
    / total_sales_exposure
    * 100
    if total_sales_exposure > 0
    else 0
)

print("\n" + "=" * 70)
print("PROFIT IMPACT SUMMARY")
print("=" * 70)

print(
    "Approved reallocations:",
    len(profit_impact_table)
)

print(
    f"Total sales exposure: "
    f"${total_sales_exposure:,.2f}"
)

print(
    f"Total gross profit exposure: "
    f"${total_profit_exposure:,.2f}"
)

print(
    f"Weighted profit margin: "
    f"{weighted_profit_margin:.2f}%"
)

print(
    f"Estimated total lead-time days saved: "
    f"{total_days_saved:,.2f}"
)

print("\nStep 10.16 completed successfully.")

======================================================================
STEP 10.16 — PROFIT IMPACT ANALYSIS
======================================================================

======================================================================
APPROVED REALLOCATIONS — PROFIT IMPACT
======================================================================

,Product ID,Product Name,Current Factory,Alternative Factory,Orders,Total Units,Total Sales,Total Gross Profit,Profit_Margin_%,Predicted Lead Time Reduction,Predicted Improvement %,Estimated Total Days Saved,Confidence Score,Risk Level,Profit Impact,Recommendation
3,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Sugar Shack,2015,7596,28485.00,18610.20,65.33,8.01,0.60,60843.96,70.59,Low Risk,High,Recommended
4,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Sugar Shack,1810,6755,23574.95,16819.95,71.35,5.61,0.42,37895.55,70.42,Low Risk,High,Recommended

======================================================================
PROFIT IMPACT SUMMARY
======================================================================
Approved reallocations: 2
Total sales exposure: $52,059.95
Total gross profit exposure: $35,430.15
Weighted profit margin: 68.06%
Estimated total lead-time days saved: 98,739.51

Step 10.16 completed successfully.

In [29]:
# ================================================================
# STEP 10.17 — FINAL RECOMMENDATION SCORE
# ================================================================

print("=" * 70)
print("STEP 10.17 — FINAL RECOMMENDATION SCORE")
print("=" * 70)

# ------------------------------------------------
# 1. Start from the approved recommendations
# ------------------------------------------------

final_score_table = profit_impact_table.copy()

# ------------------------------------------------
# 2. Normalize shipping improvement
# ------------------------------------------------
# Improvement of 5% or more receives the maximum
# shipping-benefit score of 100.

final_score_table["Shipping_Benefit_Score"] = (
    final_score_table["Predicted Improvement %"]
    .clip(lower=0, upper=5)
    / 5
    * 100
)

# ------------------------------------------------
# 3. Confidence score
# ------------------------------------------------

final_score_table["Confidence_Score"] = (
    final_score_table["Confidence Score"]
)

# ------------------------------------------------
# 4. Profitability score
# ------------------------------------------------
# Products with a gross-profit margin of 70% or more
# receive the maximum profitability score.

final_score_table["Profitability_Score"] = (
    final_score_table["Profit_Margin_%"]
    .clip(lower=0, upper=70)
    / 70
    * 100
)

# ------------------------------------------------
# 5. Risk score
# ------------------------------------------------
# Low Risk = 100
# Medium Risk = 60
# High Risk = 20

risk_score_map = {
    "Low Risk": 100,
    "Medium Risk": 60,
    "High Risk": 20
}

final_score_table["Risk_Score"] = (
    final_score_table["Risk Level"]
    .map(risk_score_map)
    .fillna(20)
)

# ------------------------------------------------
# 6. Weighted final recommendation score
# ------------------------------------------------
# Shipping improvement = 40%
# Confidence         = 30%
# Profitability      = 20%
# Risk               = 10%

final_score_table["Recommendation Score"] = (
    0.40 * final_score_table["Shipping_Benefit_Score"]
    + 0.30 * final_score_table["Confidence_Score"]
    + 0.20 * final_score_table["Profitability_Score"]
    + 0.10 * final_score_table["Risk_Score"]
)

final_score_table["Recommendation Score"] = (
    final_score_table["Recommendation Score"]
    .clip(lower=0, upper=100)
    .round(2)
)

# ------------------------------------------------
# 7. Final decision
# ------------------------------------------------

def final_decision(score):
    if score >= 70:
        return "Strong Recommendation"
    elif score >= 50:
        return "Recommendation"
    else:
        return "Review"

final_score_table["Final Decision"] = (
    final_score_table["Recommendation Score"]
    .apply(final_decision)
)

# ------------------------------------------------
# 8. Sort by final score
# ------------------------------------------------

final_score_table = (
    final_score_table
    .sort_values(
        "Recommendation Score",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------
# 9. Display final recommendation table
# ------------------------------------------------

print("\n" + "=" * 70)
print("FINAL FACTORY REALLOCATION RECOMMENDATIONS")
print("=" * 70)

display(
    final_score_table[
        [
            "Product ID",
            "Product Name",
            "Current Factory",
            "Alternative Factory",
            "Predicted Lead Time Reduction",
            "Predicted Improvement %",
            "Total Gross Profit",
            "Profit_Margin_%",
            "Confidence Score",
            "Risk Level",
            "Shipping_Benefit_Score",
            "Profitability_Score",
            "Risk_Score",
            "Recommendation Score",
            "Final Decision"
        ]
    ]
)

# ------------------------------------------------
# 10. Summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RECOMMENDATION SUMMARY")
print("=" * 70)

print(
    "Strong Recommendations:",
    (
        final_score_table["Final Decision"]
        == "Strong Recommendation"
    ).sum()
)

print(
    "Recommendations:",
    (
        final_score_table["Final Decision"]
        == "Recommendation"
    ).sum()
)

print(
    "Review:",
    (
        final_score_table["Final Decision"]
        == "Review"
    ).sum()
)

print(
    "Average Recommendation Score:",
    round(
        final_score_table[
            "Recommendation Score"
        ].mean(),
        2
    )
)

print("\nStep 10.17 completed successfully.")

======================================================================
STEP 10.17 — FINAL RECOMMENDATION SCORE
======================================================================

======================================================================
FINAL FACTORY REALLOCATION RECOMMENDATIONS
======================================================================

,Product ID,Product Name,Current Factory,Alternative Factory,Predicted Lead Time Reduction,Predicted Improvement %,Total Gross Profit,Profit_Margin_%,Confidence Score,Risk Level,Shipping_Benefit_Score,Profitability_Score,Risk_Score,Recommendation Score,Final Decision
0,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Sugar Shack,8.01,0.60,18610.20,65.33,70.59,Low Risk,12.0,93.328571,100,54.64,Recommendation
1,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Sugar Shack,5.61,0.42,16819.95,71.35,70.42,Low Risk,8.4,100.000000,100,54.49,Recommendation

======================================================================
FINAL RECOMMENDATION SUMMARY
======================================================================
Strong Recommendations: 0
Recommendations: 2
Review: 0
Average Recommendation Score: 54.56

Step 10.17 completed successfully.

In [31]:
# ================================================================
# STEP 10.18 — FINAL KPI CALCULATION
# ================================================================

print("=" * 70)
print("STEP 10.18 — FINAL KPI CALCULATION")
print("=" * 70)

# ------------------------------------------------
# 1. Lead Time Reduction KPI
# ------------------------------------------------

average_lead_time_reduction = (
    final_score_table["Predicted Lead Time Reduction"]
    .mean()
)

average_lead_time_reduction_pct = (
    final_score_table["Predicted Improvement %"]
    .mean()
)

# ------------------------------------------------
# 2. Profit Impact Stability KPI
# ------------------------------------------------
# We measure the share of recommended products
# with strong gross-profit margins (>= 50%).

profit_stable_count = (
    final_score_table["Profit_Margin_%"] >= 50
).sum()

total_recommendations = len(final_score_table)

if total_recommendations > 0:
    profit_impact_stability = (
        profit_stable_count
        / total_recommendations
        * 100
    )
else:
    profit_impact_stability = 0

# ------------------------------------------------
# 3. Scenario Confidence Score KPI
# ------------------------------------------------

average_confidence_score = (
    final_score_table["Confidence Score"].mean()
)

# ------------------------------------------------
# 4. Recommendation Coverage KPI
# ------------------------------------------------
# Number of final recommendations compared with
# total candidate products identified in Step 10.13.

total_candidates = (
    reallocation_candidates["Product ID"]
    .nunique()
)

if total_candidates > 0:
    recommendation_coverage = (
        total_recommendations
        / total_candidates
        * 100
    )
else:
    recommendation_coverage = 0

# ------------------------------------------------
# 5. Final KPI table
# ------------------------------------------------

kpi_summary = pd.DataFrame({
    "KPI": [
        "Average Lead Time Reduction",
        "Average Lead Time Reduction %",
        "Profit Impact Stability",
        "Average Scenario Confidence Score",
        "Recommendation Coverage"
    ],
    "Value": [
        round(average_lead_time_reduction, 2),
        round(average_lead_time_reduction_pct, 2),
        round(profit_impact_stability, 2),
        round(average_confidence_score, 2),
        round(recommendation_coverage, 2)
    ],
    "Unit": [
        "days",
        "%",
        "%",
        "score / 100",
        "%"
    ]
})

print("\n" + "=" * 70)
print("FINAL KPI SUMMARY")
print("=" * 70)

display(kpi_summary)

# ------------------------------------------------
# 6. Detailed KPI interpretation
# ------------------------------------------------

print("\n" + "=" * 70)
print("KPI INTERPRETATION")
print("=" * 70)

print(
    f"Average predicted lead-time reduction: "
    f"{average_lead_time_reduction:.2f} days"
)

print(
    f"Average predicted lead-time improvement: "
    f"{average_lead_time_reduction_pct:.2f}%"
)

print(
    f"Profit impact stability: "
    f"{profit_impact_stability:.2f}%"
)

print(
    f"Average scenario confidence score: "
    f"{average_confidence_score:.2f}/100"
)

print(
    f"Recommendation coverage: "
    f"{recommendation_coverage:.2f}%"
)

print("\nStep 10.18 completed successfully.")

======================================================================
STEP 10.18 — FINAL KPI CALCULATION
======================================================================

======================================================================
FINAL KPI SUMMARY
======================================================================

                                 KPI   Value         Unit
0        Average Lead Time Reduction    6.81         days
1      Average Lead Time Reduction %    0.51            %
2            Profit Impact Stability  100.00            %
3  Average Scenario Confidence Score   70.50  score / 100
4            Recommendation Coverage   28.57            %

======================================================================
KPI INTERPRETATION
======================================================================
Average predicted lead-time reduction: 6.81 days
Average predicted lead-time improvement: 0.51%
Profit impact stability: 100.00%
Average scenario confidence score: 70.50/100
Recommendation coverage: 28.57%

Step 10.18 completed successfully.

In [33]:
# ================================================================
# STEP 10.19 — FINAL RECOMMENDATION DATASET
# ================================================================

print("=" * 70)
print("STEP 10.19 — FINAL RECOMMENDATION DATASET")
print("=" * 70)

# ------------------------------------------------
# 1. Select the final recommendation columns
# ------------------------------------------------

final_recommendations = final_score_table[
    [
        "Product ID",
        "Product Name",
        "Current Factory",
        "Alternative Factory",
        "Predicted Lead Time Reduction",
        "Predicted Improvement %",
        "Total Units",
        "Total Sales",
        "Total Gross Profit",
        "Profit_Margin_%",
        "Confidence Score",
        "Risk Level",
        "Recommendation Score",
        "Final Decision"
    ]
].copy()

# ------------------------------------------------
# 2. Rename columns for cleaner dashboard/report use
# ------------------------------------------------

final_recommendations = final_recommendations.rename(
    columns={
        "Alternative Factory": "Recommended Factory",
        "Predicted Lead Time Reduction": "Predicted Days Saved",
        "Predicted Improvement %": "Lead Time Improvement %",
        "Total Units": "Affected Units",
        "Total Sales": "Affected Sales",
        "Total Gross Profit": "Affected Gross Profit",
        "Profit_Margin_%": "Profit Margin %",
        "Confidence Score": "Scenario Confidence Score",
        "Recommendation Score": "Final Recommendation Score"
    }
)

# ------------------------------------------------
# 3. Sort by recommendation score
# ------------------------------------------------

final_recommendations = (
    final_recommendations
    .sort_values(
        "Final Recommendation Score",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------
# 4. Round numerical columns
# ------------------------------------------------

numeric_columns = [
    "Predicted Days Saved",
    "Lead Time Improvement %",
    "Affected Sales",
    "Affected Gross Profit",
    "Profit Margin %",
    "Scenario Confidence Score",
    "Final Recommendation Score"
]

final_recommendations[numeric_columns] = (
    final_recommendations[numeric_columns].round(2)
)

# ------------------------------------------------
# 5. Display final recommendation dataset
# ------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RECOMMENDATION DATASET")
print("=" * 70)

display(final_recommendations)

# ------------------------------------------------
# 6. Summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RECOMMENDATION DATASET SUMMARY")
print("=" * 70)

print(
    "Final recommendations:",
    len(final_recommendations)
)

print(
    "Recommended products:",
    final_recommendations["Product Name"].nunique()
)

if not final_recommendations.empty:

    print(
        "Average predicted days saved:",
        round(
            final_recommendations["Predicted Days Saved"].mean(),
            2
        )
    )

    print(
        "Average scenario confidence:",
        round(
            final_recommendations["Scenario Confidence Score"].mean(),
            2
        )
    )

    print(
        "Average recommendation score:",
        round(
            final_recommendations["Final Recommendation Score"].mean(),
            2
        )
    )

print("\nStep 10.19 completed successfully.")

======================================================================
STEP 10.19 — FINAL RECOMMENDATION DATASET
======================================================================

======================================================================
FINAL RECOMMENDATION DATASET
======================================================================

,Product ID,Product Name,Current Factory,Recommended Factory,Predicted Days Saved,Lead Time Improvement %,Affected Units,Affected Sales,Affected Gross Profit,Profit Margin %,Scenario Confidence Score,Risk Level,Final Recommendation Score,Final Decision
0,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Sugar Shack,8.01,0.60,7596,28485.00,18610.20,65.33,70.59,Low Risk,54.64,Recommendation
1,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Sugar Shack,5.61,0.42,6755,23574.95,16819.95,71.35,70.42,Low Risk,54.49,Recommendation

======================================================================
FINAL RECOMMENDATION DATASET SUMMARY
======================================================================
Final recommendations: 2
Recommended products: 2
Average predicted days saved: 6.81
Average scenario confidence: 70.5
Average recommendation score: 54.56

Step 10.19 completed successfully.

In [35]:
#The ML scenario engine identifies two candidate reallocations with positive predicted lead-time improvement. These are model-based recommendations requiring operational validation before implementation